<a href="https://colab.research.google.com/github/Glockrover/LearnTensorFlow/blob/main/Exercises/01_NeuralNetwork_excercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🛠 01. Neural network regression with TensorFlow Exercises

1. Create your own regression dataset (or make the one we created in "Create data to view and fit" bigger) and build fit a model to it.

2. Try building a neural network with 4 Dense layers and fitting it to your own regression dataset, how does it perform?

3. Try and improve the results we got on the insurance dataset, some things you might want to try include:
  * Building a larger model (how does one with 4 dense layers go?).
  * Increasing the number of units in each layer.
  * Lookup the documentation of Adam and find out what the first parameter is, what happens if you increase it by 10x?
  * What happens if you train for longer (say 300 epochs instead of 200)?
  
4. Import the Boston pricing dataset from TensorFlow tf.keras.datasets and model it.

## 📖 01. Neural network regression with TensorFlow Extra-curriculum

* [MIT introduction deep learning lecture 1](https://www.youtube.com/watch?v=7sB052Pz0sQ&ab_channel=AlexanderAmini) - gives a great overview of what's happening behind all of the code we're running.

* Reading: 1-hour of [Chapter 1 of Neural Networks and Deep Learning](http://neuralnetworksanddeeplearning.com/chap1.html) by Michael Nielson - a great in-depth and hands-on example of the intuition behind neural networks.

* To practice your regression modelling with TensorFlow, I'd also encourage you to look through [Kaggle's datasets](https://www.kaggle.com/data), find a regression dataset which sparks your interest and try to model.

## 1. Creating our own data set

We are going to use a simple yet powerful way of seeing if our deep learing model works.
The equation is simple `f(x) = 2x`.
![Equation](https://substackcdn.com/image/fetch/$s_!IeZt!,w_1200,h_675,c_fill,f_jpg,q_auto:good,fl_progressive:steep,g_auto/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fc0070a50-7da3-43bb-903c-8249d7d08dcb_1600x608.jpeg)

In [ ]:
# First we going to create the dataset
X = [n for n in range(1000)]
y = [n * 2 for n in range(1000)]

In [ ]:
import tensorflow as tf

X = tf.constant(tf.expand_dims(X, axis=-1))
y = tf.constant(tf.expand_dims(y, axis=-1))

# Creating our model
model1 = tf.keras.Sequential([
    tf.keras.layers.Dense(1),

])

# Compile the model
model1.compile(loss=tf.losses.mae,
               optimizer=tf.optimizers.SGD(),
               metrics=["mae"])

# Fitting the model
model1.fit(X, y, epochs=200)

Epoch 1/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1262.5665 - mae: 1262.5665
Epoch 2/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1266.6940 - mae: 1266.6940
Epoch 3/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1260.9030 - mae: 1260.9030
Epoch 4/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1295.8898 - mae: 1295.8898
Epoch 5/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1260.4312 - mae: 1260.4312
Epoch 6/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1280.6976 - mae: 1280.6976
Epoch 7/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1250.6580 - mae: 1250.6580
Epoch 8/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1244.9253 - mae: 1244.9253
Epoch 9/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1287.0975 - mae: 1287.0975
Epoch 10/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1267.1237 - mae: 1267.1237
Epoch 11/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1274.0785 - mae: 1274.0785
Epoch 12/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1283.2756 - mae: 1283.2756
Epoch 13/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1290.8832 - mae: 1290.8832
Epoch 14/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1272.6450 - mae: 1272.6450
Epoch 15/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1241.0273 - mae: 1241.0273
Epoch 16/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1229.6881 - mae: 1229.6881
Epoch 17/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1231.9436 - mae: 1231.9436
Epoch 18/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1254.3009 - mae: 1254.3009
Epoch 19/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1282.9867 - mae: 1282.9867
Epoch 20/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1265.5732 - mae: 1265.5732
Epoch 21/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1278.1337 - mae: 1278.1337
Epoch 22/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1272.0311 - mae: 1272.0311
Epoch 23/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1274.2966 - mae: 1274.2966
Epoch 24/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1291.5157 - mae: 1291.5157
Epoch 25/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1249.0259 - mae: 1249.0259
Epoch 26/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1285.8615 - mae: 1285.8615
Epoch 27/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1262.7698 - mae: 1262.7698
Epoch 28/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1291.3146 - mae: 1291.3146
Epoch 29/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1249.1061 - mae: 1249.1061
Epoch 30/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1268.9247 - mae: 1268.9247
Epoch 31/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1250.8159 - mae: 1250.8159
Epoch 32/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1249.7184 - mae: 1249.7184
Epoch 33/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1232.0037 - mae: 1232.0037
Epoch 34/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1237.2114 - mae: 1237.2114
Epoch 35/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1246.2240 - mae: 1246.2240
Epoch 36/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1271.5743 - mae: 1271.5743
Epoch 37/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1232.3098 - mae: 1232.3098
Epoch 38/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1249.4832 - mae: 1249.4832
Epoch 39/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1259.2993 - mae: 1259.2993
Epoch 40/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1270.9801 - mae: 1270.9801
Epoch 41/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1230.2070 - mae: 1230.2070
Epoch 42/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1254.8436 - mae: 1254.8436
Epoch 43/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1266.7819 - mae: 1266.7819
Epoch 44/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1260.3112 - mae: 1260.3112
Epoch 45/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1275.3969 - mae: 1275.3969
Epoch 46/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1279.5713 - mae: 1279.5713
Epoch 47/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1273.8779 - mae: 1273.8779
Epoch 48/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1255.2926 - mae: 1255.2926
Epoch 49/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1274.4493 - mae: 1274.4493
Epoch 50/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1264.1823 - mae: 1264.1823
Epoch 51/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1279.5901 - mae: 1279.5901
Epoch 52/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1244.0610 - mae: 1244.0610
Epoch 53/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1248.2174 - mae: 1248.2174
Epoch 54/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1275.6831 - mae: 1275.6831
Epoch 55/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1284.6561 - mae: 1284.6561
Epoch 56/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1280.1050 - mae: 1280.1050
Epoch 57/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1252.6221 - mae: 1252.6221
Epoch 58/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1255.4330 - mae: 1255.4330
Epoch 59/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1239.2828 - mae: 1239.2828
Epoch 60/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1248.0792 - mae: 1248.0792
Epoch 61/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1280.9816 - mae: 1280.9816
Epoch 62/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1264.0669 - mae: 1264.0669
Epoch 63/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1277.2377 - mae: 1277.2377
Epoch 64/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1292.2971 - mae: 1292.2971
Epoch 65/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1237.4886 - mae: 1237.4886
Epoch 66/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1262.1096 - mae: 1262.1096
Epoch 67/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1274.7662 - mae: 1274.7662
Epoch 68/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1256.7872 - mae: 1256.7872
Epoch 69/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1287.9814 - mae: 1287.9814
Epoch 70/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1258.4358 - mae: 1258.4358
Epoch 71/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1282.7915 - mae: 1282.7915
Epoch 72/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1262.2245 - mae: 1262.2245
Epoch 73/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1247.0802 - mae: 1247.0802
Epoch 74/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1254.9779 - mae: 1254.9779
Epoch 75/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1264.4701 - mae: 1264.4701
Epoch 76/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1264.6051 - mae: 1264.6051
Epoch 77/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1242.4867 - mae: 1242.4867
Epoch 78/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1244.2271 - mae: 1244.2271
Epoch 79/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1251.4034 - mae: 1251.4034
Epoch 80/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1280.2649 - mae: 1280.2649
Epoch 81/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1284.3539 - mae: 1284.3539
Epoch 82/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1249.5090 - mae: 1249.5090
Epoch 83/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1258.3069 - mae: 1258.3069
Epoch 84/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1260.1583 - mae: 1260.1583
Epoch 85/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1260.5923 - mae: 1260.5923
Epoch 86/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1271.3567 - mae: 1271.3567
Epoch 87/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1316.9607 - mae: 1316.9607
Epoch 88/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1261.6058 - mae: 1261.6058
Epoch 89/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1238.6165 - mae: 1238.6165
Epoch 90/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1249.1326 - mae: 1249.1326
Epoch 91/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1258.2004 - mae: 1258.2004
Epoch 92/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1257.6898 - mae: 1257.6898
Epoch 93/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1246.9587 - mae: 1246.9587
Epoch 94/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1252.5015 - mae: 1252.5015
Epoch 95/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1262.3531 - mae: 1262.3531
Epoch 96/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1245.2145 - mae: 1245.2145
Epoch 97/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1246.8097 - mae: 1246.8097
Epoch 98/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1232.7485 - mae: 1232.7485
Epoch 99/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1250.6785 - mae: 1250.6785
Epoch 100/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1261.0552 - mae: 1261.0552
Epoch 101/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1281.5751 - mae: 1281.5751
Epoch 102/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1253.3628 - mae: 1253.3628
Epoch 103/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1245.1818 - mae: 1245.1818
Epoch 104/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1255.5684 - mae: 1255.5684
Epoch 105/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1261.8337 - mae: 1261.8337
Epoch 106/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1249.0154 - mae: 1249.0154
Epoch 107/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1262.5211 - mae: 1262.5211
Epoch 108/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1256.8352 - mae: 1256.8352
Epoch 109/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1260.6890 - mae: 1260.6890
Epoch 110/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1256.1006 - mae: 1256.1006
Epoch 111/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1283.1813 - mae: 1283.1813
Epoch 112/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1262.5105 - mae: 1262.5105
Epoch 113/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1319.7977 - mae: 1319.7977
Epoch 114/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1243.3806 - mae: 1243.3806
Epoch 115/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1250.6274 - mae: 1250.6274
Epoch 116/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1274.5074 - mae: 1274.5074
Epoch 117/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1287.5996 - mae: 1287.5996
Epoch 118/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1258.2268 - mae: 1258.2268
Epoch 119/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1244.4967 - mae: 1244.4967
Epoch 120/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1247.8708 - mae: 1247.8708
Epoch 121/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1256.2157 - mae: 1256.2157
Epoch 122/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1259.6523 - mae: 1259.6523
Epoch 123/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1275.3287 - mae: 1275.3287
Epoch 124/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1257.7823 - mae: 1257.7823
Epoch 125/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1281.5846 - mae: 1281.5846
Epoch 126/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1276.0228 - mae: 1276.0228
Epoch 127/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1263.0605 - mae: 1263.0605
Epoch 128/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1262.5164 - mae: 1262.5164
Epoch 129/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1274.6790 - mae: 1274.6790
Epoch 130/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1286.0537 - mae: 1286.0537
Epoch 131/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1250.7617 - mae: 1250.7617
Epoch 132/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1271.7788 - mae: 1271.7788
Epoch 133/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1254.1593 - mae: 1254.1593
Epoch 134/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1261.8147 - mae: 1261.8147
Epoch 135/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1254.1692 - mae: 1254.1692
Epoch 136/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1258.6823 - mae: 1258.6823
Epoch 137/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1269.9962 - mae: 1269.9962
Epoch 138/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1269.6201 - mae: 1269.6201
Epoch 139/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1240.2793 - mae: 1240.2793
Epoch 140/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1229.9907 - mae: 1229.9907
Epoch 141/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1251.3965 - mae: 1251.3965
Epoch 142/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1282.3813 - mae: 1282.3813
Epoch 143/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1254.4485 - mae: 1254.4485
Epoch 144/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1251.8433 - mae: 1251.8433
Epoch 145/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1261.2415 - mae: 1261.2415
Epoch 146/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1258.6072 - mae: 1258.6072
Epoch 147/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1244.7872 - mae: 1244.7872
Epoch 148/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1245.0101 - mae: 1245.0101
Epoch 149/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1246.2479 - mae: 1246.2479
Epoch 150/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1246.8469 - mae: 1246.8469
Epoch 151/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1269.5510 - mae: 1269.5510
Epoch 152/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1257.2941 - mae: 1257.2941
Epoch 153/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1248.1000 - mae: 1248.1000
Epoch 154/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1242.8331 - mae: 1242.8331
Epoch 155/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1308.8641 - mae: 1308.8641
Epoch 156/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1239.8898 - mae: 1239.8898
Epoch 157/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1248.7799 - mae: 1248.7799
Epoch 158/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1306.8109 - mae: 1306.8109
Epoch 159/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1285.9210 - mae: 1285.9210
Epoch 160/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1277.7512 - mae: 1277.7512
Epoch 161/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1254.8331 - mae: 1254.8331
Epoch 162/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1237.8813 - mae: 1237.8813
Epoch 163/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1246.2941 - mae: 1246.2941
Epoch 164/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1249.0276 - mae: 1249.0276
Epoch 165/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1245.9221 - mae: 1245.9221
Epoch 166/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1264.4055 - mae: 1264.4055
Epoch 167/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1255.6689 - mae: 1255.6689
Epoch 168/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1253.0214 - mae: 1253.0214
Epoch 169/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1245.8787 - mae: 1245.8787
Epoch 170/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1249.0293 - mae: 1249.0293
Epoch 171/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1241.5898 - mae: 1241.5898
Epoch 172/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1248.0983 - mae: 1248.0983
Epoch 173/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1242.2810 - mae: 1242.2810
Epoch 174/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1233.8508 - mae: 1233.8508
Epoch 175/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1228.0431 - mae: 1228.0431
Epoch 176/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1255.1665 - mae: 1255.1665
Epoch 177/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1264.3192 - mae: 1264.3192
Epoch 178/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1278.4467 - mae: 1278.4467
Epoch 179/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1235.9697 - mae: 1235.9697
Epoch 180/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1234.0128 - mae: 1234.0128
Epoch 181/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1256.5774 - mae: 1256.5774
Epoch 182/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1271.1611 - mae: 1271.1611
Epoch 183/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1289.9677 - mae: 1289.9677
Epoch 184/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1257.9498 - mae: 1257.9498
Epoch 185/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1276.4200 - mae: 1276.4200
Epoch 186/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1258.1754 - mae: 1258.1754
Epoch 187/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1261.6562 - mae: 1261.6562
Epoch 188/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1255.1788 - mae: 1255.1788
Epoch 189/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1247.9546 - mae: 1247.9546
Epoch 190/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1250.6289 - mae: 1250.6289
Epoch 191/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1250.5774 - mae: 1250.5774
Epoch 192/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1292.1052 - mae: 1292.1052
Epoch 193/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1253.3416 - mae: 1253.3416
Epoch 194/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1263.1010 - mae: 1263.1010
Epoch 195/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1257.4847 - mae: 1257.4847
Epoch 196/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1263.3783 - mae: 1263.3783
Epoch 197/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1274.4060 - mae: 1274.4060
Epoch 198/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1262.7454 - mae: 1262.7454
Epoch 199/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1257.4072 - mae: 1257.4072
Epoch 200/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1226.7384 - mae: 1226.7384

In [ ]:
# Predict the number from our model
input = tf.constant([1000])
input = tf.expand_dims(input, axis=-1)
model1.predict(input)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step

array([[1369.4807]], dtype=float32)

## Try building a neural network with 4 Dense layers and fitting it to your own regression dataset, how does it perform?

In [ ]:
# Creating our model
model2 = tf.keras.Sequential([
    tf.keras.layers.Dense(100, input_shape=(1,)),
    tf.keras.layers.Dense(50),
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1)

])

# Compile the model
model1.compile(loss=tf.losses.mae,
               optimizer=tf.optimizers.SGD(),
               metrics=["mae"])

# Fitting the model
model1.fit(X, y, epochs=200)

Epoch 1/200

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1240.7590 - mae: 1240.7590
Epoch 2/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1266.5420 - mae: 1266.5420
Epoch 3/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1274.9762 - mae: 1274.9762
Epoch 4/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1240.8392 - mae: 1240.8392
Epoch 5/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1252.5674 - mae: 1252.5674
Epoch 6/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1249.5938 - mae: 1249.5938
Epoch 7/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1252.5671 - mae: 1252.5671
Epoch 8/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1263.8483 - mae: 1263.8483
Epoch 9/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1256.0941 - mae: 1256.0941
Epoch 10/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1255.1333 - mae: 1255.1333
Epoch 11/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1251.6255 - mae: 1251.6255
Epoch 12/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1269.0641 - mae: 1269.0641
Epoch 13/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1269.8015 - mae: 1269.8015
Epoch 14/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1268.1155 - mae: 1268.1155
Epoch 15/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1282.1865 - mae: 1282.1865
Epoch 16/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1249.7136 - mae: 1249.7136
Epoch 17/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1252.5726 - mae: 1252.5726
Epoch 18/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1267.6819 - mae: 1267.6819
Epoch 19/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1274.6238 - mae: 1274.6238
Epoch 20/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1271.2219 - mae: 1271.2219
Epoch 21/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1277.8667 - mae: 1277.8667
Epoch 22/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1279.9779 - mae: 1279.9779
Epoch 23/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1279.6195 - mae: 1279.6195
Epoch 24/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1235.4191 - mae: 1235.4191
Epoch 25/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1235.6173 - mae: 1235.6173
Epoch 26/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1258.1355 - mae: 1258.1355
Epoch 27/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1243.2871 - mae: 1243.2871
Epoch 28/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1280.2687 - mae: 1280.2687
Epoch 29/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1244.1072 - mae: 1244.1072
Epoch 30/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1251.7701 - mae: 1251.7701
Epoch 31/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1251.2960 - mae: 1251.2960
Epoch 32/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1242.0719 - mae: 1242.0719
Epoch 33/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1252.5258 - mae: 1252.5258
Epoch 34/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1237.4388 - mae: 1237.4388
Epoch 35/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1235.2290 - mae: 1235.2290
Epoch 36/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1257.3793 - mae: 1257.3793
Epoch 37/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1265.1615 - mae: 1265.1615
Epoch 38/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1276.9293 - mae: 1276.9293
Epoch 39/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1289.4099 - mae: 1289.4099
Epoch 40/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1282.6915 - mae: 1282.6915
Epoch 41/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1252.9910 - mae: 1252.9910
Epoch 42/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1243.6124 - mae: 1243.6124
Epoch 43/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1255.4109 - mae: 1255.4109
Epoch 44/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1255.4760 - mae: 1255.4760
Epoch 45/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1238.9464 - mae: 1238.9464
Epoch 46/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1251.4604 - mae: 1251.4604
Epoch 47/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1257.3287 - mae: 1257.3287
Epoch 48/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1246.6790 - mae: 1246.6790
Epoch 49/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1301.2493 - mae: 1301.2493
Epoch 50/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1260.1951 - mae: 1260.1951
Epoch 51/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1265.2830 - mae: 1265.2830
Epoch 52/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1284.3483 - mae: 1284.3483
Epoch 53/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1256.8818 - mae: 1256.8818
Epoch 54/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1245.1793 - mae: 1245.1793
Epoch 55/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1258.8827 - mae: 1258.8827
Epoch 56/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1258.4601 - mae: 1258.4601
Epoch 57/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1250.8939 - mae: 1250.8939
Epoch 58/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1252.5841 - mae: 1252.5841
Epoch 59/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1240.4808 - mae: 1240.4808
Epoch 60/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1244.7522 - mae: 1244.7522
Epoch 61/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1250.0844 - mae: 1250.0844
Epoch 62/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1262.7454 - mae: 1262.7454
Epoch 63/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1284.4795 - mae: 1284.4795
Epoch 64/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1261.5813 - mae: 1261.5813
Epoch 65/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1254.4047 - mae: 1254.4047
Epoch 66/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1254.2064 - mae: 1254.2064
Epoch 67/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1285.0295 - mae: 1285.0295
Epoch 68/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1292.9475 - mae: 1292.9475
Epoch 69/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1278.2056 - mae: 1278.2056
Epoch 70/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1273.4670 - mae: 1273.4670
Epoch 71/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1273.2301 - mae: 1273.2301
Epoch 72/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1248.7584 - mae: 1248.7584
Epoch 73/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1263.3473 - mae: 1263.3473
Epoch 74/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1256.0374 - mae: 1256.0374
Epoch 75/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1252.8933 - mae: 1252.8933
Epoch 76/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1253.4191 - mae: 1253.4191
Epoch 77/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1270.5555 - mae: 1270.5555
Epoch 78/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1272.3573 - mae: 1272.3573
Epoch 79/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1271.9438 - mae: 1271.9438
Epoch 80/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1249.9553 - mae: 1249.9553
Epoch 81/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1253.4094 - mae: 1253.4094
Epoch 82/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1248.5725 - mae: 1248.5725
Epoch 83/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1266.5948 - mae: 1266.5948
Epoch 84/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1266.4708 - mae: 1266.4708
Epoch 85/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1253.0674 - mae: 1253.0674
Epoch 86/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1261.9956 - mae: 1261.9956
Epoch 87/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1251.6906 - mae: 1251.6906
Epoch 88/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1226.8468 - mae: 1226.8468
Epoch 89/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1239.1365 - mae: 1239.1365
Epoch 90/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1243.6943 - mae: 1243.6943
Epoch 91/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1257.1658 - mae: 1257.1658
Epoch 92/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1259.3718 - mae: 1259.3718
Epoch 93/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1241.0972 - mae: 1241.0972
Epoch 94/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1239.6033 - mae: 1239.6033
Epoch 95/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1227.7263 - mae: 1227.7263
Epoch 96/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1259.2449 - mae: 1259.2449
Epoch 97/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1261.1062 - mae: 1261.1062
Epoch 98/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1282.1008 - mae: 1282.1008
Epoch 99/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1276.3411 - mae: 1276.3411
Epoch 100/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1241.3304 - mae: 1241.3304
Epoch 101/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1249.8406 - mae: 1249.8406
Epoch 102/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1249.1859 - mae: 1249.1859
Epoch 103/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1273.3717 - mae: 1273.3717
Epoch 104/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1262.8698 - mae: 1262.8698
Epoch 105/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1266.0229 - mae: 1266.0229
Epoch 106/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1259.6866 - mae: 1259.6866
Epoch 107/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1260.7499 - mae: 1260.7499
Epoch 108/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1290.2284 - mae: 1290.2284
Epoch 109/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1260.8710 - mae: 1260.8710
Epoch 110/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1248.5592 - mae: 1248.5592
Epoch 111/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1248.4664 - mae: 1248.4664
Epoch 112/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1247.8783 - mae: 1247.8783
Epoch 113/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1238.8169 - mae: 1238.8169
Epoch 114/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1244.7914 - mae: 1244.7914
Epoch 115/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1246.5980 - mae: 1246.5980
Epoch 116/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1251.1090 - mae: 1251.1090
Epoch 117/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1252.3990 - mae: 1252.3990
Epoch 118/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1254.4204 - mae: 1254.4204
Epoch 119/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1293.4036 - mae: 1293.4036
Epoch 120/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1246.2034 - mae: 1246.2034
Epoch 121/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1279.8000 - mae: 1279.8000
Epoch 122/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1278.8693 - mae: 1278.8693
Epoch 123/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1272.7716 - mae: 1272.7716
Epoch 124/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1311.4598 - mae: 1311.4598
Epoch 125/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1253.5406 - mae: 1253.5406
Epoch 126/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1261.9825 - mae: 1261.9825
Epoch 127/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1302.2537 - mae: 1302.2537
Epoch 128/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1242.9226 - mae: 1242.9226
Epoch 129/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1263.3405 - mae: 1263.3405
Epoch 130/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1258.0052 - mae: 1258.0052
Epoch 131/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1255.7494 - mae: 1255.7494
Epoch 132/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1253.4476 - mae: 1253.4476
Epoch 133/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1309.6732 - mae: 1309.6732
Epoch 134/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1262.7643 - mae: 1262.7643
Epoch 135/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1297.5439 - mae: 1297.5439
Epoch 136/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1228.0663 - mae: 1228.0663
Epoch 137/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1243.5699 - mae: 1243.5699
Epoch 138/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1248.1460 - mae: 1248.1460
Epoch 139/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1256.8196 - mae: 1256.8196
Epoch 140/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1257.8402 - mae: 1257.8402
Epoch 141/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1234.8773 - mae: 1234.8773
Epoch 142/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1248.8992 - mae: 1248.8992
Epoch 143/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1299.8060 - mae: 1299.8060
Epoch 144/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1273.0887 - mae: 1273.0887
Epoch 145/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1287.6979 - mae: 1287.6979
Epoch 146/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1265.2069 - mae: 1265.2069
Epoch 147/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1269.7546 - mae: 1269.7546
Epoch 148/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1266.6246 - mae: 1266.6246
Epoch 149/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1274.7599 - mae: 1274.7599
Epoch 150/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1277.7992 - mae: 1277.7992
Epoch 151/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1267.9128 - mae: 1267.9128
Epoch 152/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1270.4889 - mae: 1270.4889
Epoch 153/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1257.4484 - mae: 1257.4484
Epoch 154/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1248.8595 - mae: 1248.8595
Epoch 155/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1251.4137 - mae: 1251.4137
Epoch 156/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1306.6262 - mae: 1306.6262
Epoch 157/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1262.5128 - mae: 1262.5128
Epoch 158/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1318.9896 - mae: 1318.9896
Epoch 159/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1241.3141 - mae: 1241.3141
Epoch 160/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1239.1014 - mae: 1239.1014
Epoch 161/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1261.0128 - mae: 1261.0128
Epoch 162/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1289.0090 - mae: 1289.0090
Epoch 163/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1230.1205 - mae: 1230.1205
Epoch 164/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1258.0187 - mae: 1258.0187
Epoch 165/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1251.2761 - mae: 1251.2761
Epoch 166/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1236.6312 - mae: 1236.6312
Epoch 167/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1235.1321 - mae: 1235.1321
Epoch 168/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1252.6475 - mae: 1252.6475
Epoch 169/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1256.1492 - mae: 1256.1492
Epoch 170/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1260.2856 - mae: 1260.2856
Epoch 171/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1286.2922 - mae: 1286.2922
Epoch 172/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1257.4241 - mae: 1257.4241
Epoch 173/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1270.9941 - mae: 1270.9941
Epoch 174/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1247.4249 - mae: 1247.4249
Epoch 175/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1264.2418 - mae: 1264.2418
Epoch 176/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1292.5953 - mae: 1292.5953
Epoch 177/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1288.2518 - mae: 1288.2518
Epoch 178/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1263.1368 - mae: 1263.1368
Epoch 179/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1268.4651 - mae: 1268.4651
Epoch 180/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1270.8336 - mae: 1270.8336
Epoch 181/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1319.4961 - mae: 1319.4961
Epoch 182/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1277.3914 - mae: 1277.3914
Epoch 183/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1266.3331 - mae: 1266.3331
Epoch 184/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1278.8003 - mae: 1278.8003
Epoch 185/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1243.7229 - mae: 1243.7229
Epoch 186/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1254.4580 - mae: 1254.4580
Epoch 187/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1302.7152 - mae: 1302.7152
Epoch 188/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1251.0828 - mae: 1251.0828
Epoch 189/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1280.1785 - mae: 1280.1785
Epoch 190/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1279.5541 - mae: 1279.5541
Epoch 191/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1297.9736 - mae: 1297.9736
Epoch 192/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1262.4811 - mae: 1262.4811
Epoch 193/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1264.4347 - mae: 1264.4347
Epoch 194/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1244.3998 - mae: 1244.3998
Epoch 195/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1251.1628 - mae: 1251.1628
Epoch 196/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1253.5145 - mae: 1253.5145
Epoch 197/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1295.8257 - mae: 1295.8257
Epoch 198/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1262.9847 - mae: 1262.9847
Epoch 199/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1255.3156 - mae: 1255.3156
Epoch 200/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1274.9430 - mae: 1274.9430

In [ ]:
input = tf.constant([1000])
input = tf.expand_dims(input, axis=-1)
model2.predict(input)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

array([[-235.68175]], dtype=float32)

Try and improve the results we got on the insurance dataset, some things you might want to try include:

Building a larger model (how does one with 4 dense layers go?).
Increasing the number of units in each layer.
Lookup the documentation of Adam and find out what the first parameter is, what happens if you increase it by 10x?
What happens if you train for longer (say 300 epochs instead of 200)?

In [ ]:
import pandas as pd

insurance = pd.read_csv("https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/refs/heads/master/insurance.csv")
insurance.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
insurance = pd.get_dummies(insurance)
insurance.head()

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,True,False,False,True,False,False,False,True
1,18,33.770,1,1725.55230,False,True,True,False,False,False,True,False
2,28,33.000,3,4449.46200,False,True,True,False,False,False,True,False
3,33,22.705,0,21984.47061,False,True,True,False,False,True,False,False
4,32,28.880,0,3866.85520,False,True,True,False,False,True,False,False

In [ ]:
from sklearn.model_selection import train_test_split

X = insurance.drop("charges", axis=1)
y = insurance["charges"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
insurance_model1 = tf.keras.Sequential([
    tf.keras.layers.Dense(100, input_shape=(11,)),
    tf.keras.layers.Dense(75),
    tf.keras.layers.Dense(20),
    tf.keras.layers.Dense(1)
])

insurance_model1.compile(loss=tf.keras.losses.mae,
                         optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
                        metrics=["mae"])

insurance_model1.fit(X_train, y_train, epochs=300)

Epoch 1/300

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8854.5117 - mae: 8854.5117
Epoch 2/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6804.8853 - mae: 6804.8853
Epoch 3/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6250.4365 - mae: 6250.4365
Epoch 4/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5898.1851 - mae: 5898.1851
Epoch 5/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5337.6919 - mae: 5337.6919
Epoch 6/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4108.1543 - mae: 4108.1543
Epoch 7/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3747.3069 - mae: 3747.3069
Epoch 8/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3785.3459 - mae: 3785.3459
Epoch 9/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4025.8181 - mae: 4025.8181
Epoch 10/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3808.8521 - mae: 3808.8521
Epoch 11/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3646.9214 - mae: 3646.9214
Epoch 12/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3661.6150 - mae: 3661.6150
Epoch 13/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3938.7197 - mae: 3938.7197
Epoch 14/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3707.5356 - mae: 3707.5356
Epoch 15/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3729.7961 - mae: 3729.7961
Epoch 16/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3639.3516 - mae: 3639.3516
Epoch 17/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3746.3022 - mae: 3746.3022
Epoch 18/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3715.5171 - mae: 3715.5171
Epoch 19/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3681.0654 - mae: 3681.0654
Epoch 20/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3638.5425 - mae: 3638.5425
Epoch 21/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3584.0444 - mae: 3584.0444
Epoch 22/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3703.9749 - mae: 3703.9749
Epoch 23/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3658.4731 - mae: 3658.4731
Epoch 24/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3665.2668 - mae: 3665.2668
Epoch 25/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3750.2344 - mae: 3750.2344
Epoch 26/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3691.9116 - mae: 3691.9116
Epoch 27/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3611.8726 - mae: 3611.8726
Epoch 28/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3649.7288 - mae: 3649.7288
Epoch 29/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3634.6313 - mae: 3634.6313
Epoch 30/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3690.6987 - mae: 3690.6987
Epoch 31/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3666.7051 - mae: 3666.7051
Epoch 32/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3606.5774 - mae: 3606.5774
Epoch 33/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3655.2334 - mae: 3655.2334
Epoch 34/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3646.6887 - mae: 3646.6887
Epoch 35/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3648.5842 - mae: 3648.5842
Epoch 36/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3638.0156 - mae: 3638.0156
Epoch 37/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3633.3987 - mae: 3633.3987
Epoch 38/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3613.2104 - mae: 3613.2104
Epoch 39/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3583.8643 - mae: 3583.8643
Epoch 40/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3710.3210 - mae: 3710.3210
Epoch 41/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3623.8242 - mae: 3623.8242
Epoch 42/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3675.4902 - mae: 3675.4902
Epoch 43/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3688.0576 - mae: 3688.0576
Epoch 44/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3679.7747 - mae: 3679.7747
Epoch 45/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3634.3289 - mae: 3634.3289
Epoch 46/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3644.4521 - mae: 3644.4521
Epoch 47/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3731.2683 - mae: 3731.2683
Epoch 48/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3615.0903 - mae: 3615.0903
Epoch 49/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3609.5828 - mae: 3609.5828
Epoch 50/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3682.5122 - mae: 3682.5122
Epoch 51/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3616.1860 - mae: 3616.1860
Epoch 52/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3623.1929 - mae: 3623.1929
Epoch 53/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3624.3506 - mae: 3624.3506
Epoch 54/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3576.2510 - mae: 3576.2510
Epoch 55/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3632.0901 - mae: 3632.0901
Epoch 56/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3719.8608 - mae: 3719.8608
Epoch 57/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3910.1467 - mae: 3910.1467
Epoch 58/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3630.0911 - mae: 3630.0911
Epoch 59/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3540.6577 - mae: 3540.6577
Epoch 60/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3625.6611 - mae: 3625.6611
Epoch 61/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3601.4692 - mae: 3601.4692
Epoch 62/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3633.0635 - mae: 3633.0635
Epoch 63/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3732.5518 - mae: 3732.5518
Epoch 64/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3589.4785 - mae: 3589.4785
Epoch 65/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3639.9001 - mae: 3639.9001
Epoch 66/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3566.6995 - mae: 3566.6995
Epoch 67/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3728.4187 - mae: 3728.4187
Epoch 68/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3659.2004 - mae: 3659.2004
Epoch 69/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3692.9636 - mae: 3692.9636
Epoch 70/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3593.4397 - mae: 3593.4397
Epoch 71/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3684.2029 - mae: 3684.2029
Epoch 72/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3654.4170 - mae: 3654.4170
Epoch 73/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3637.5181 - mae: 3637.5181
Epoch 74/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3547.1155 - mae: 3547.1155
Epoch 75/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3663.8115 - mae: 3663.8115
Epoch 76/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3656.4346 - mae: 3656.4346
Epoch 77/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3535.4568 - mae: 3535.4568
Epoch 78/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3651.3835 - mae: 3651.3835
Epoch 79/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3667.3582 - mae: 3667.3582
Epoch 80/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3617.7874 - mae: 3617.7874
Epoch 81/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3597.2664 - mae: 3597.2664
Epoch 82/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3715.8643 - mae: 3715.8643
Epoch 83/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3588.4890 - mae: 3588.4890
Epoch 84/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3581.3865 - mae: 3581.3865
Epoch 85/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3629.0144 - mae: 3629.0144
Epoch 86/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3584.5205 - mae: 3584.5205
Epoch 87/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3541.2686 - mae: 3541.2686
Epoch 88/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3575.1755 - mae: 3575.1755
Epoch 89/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3585.5823 - mae: 3585.5823
Epoch 90/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3578.7192 - mae: 3578.7192
Epoch 91/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3617.7825 - mae: 3617.7825
Epoch 92/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3545.7129 - mae: 3545.7129
Epoch 93/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3619.9412 - mae: 3619.9412
Epoch 94/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3596.5776 - mae: 3596.5776
Epoch 95/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3583.9355 - mae: 3583.9355
Epoch 96/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3596.5701 - mae: 3596.5701
Epoch 97/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3677.0942 - mae: 3677.0942
Epoch 98/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3631.4487 - mae: 3631.4487
Epoch 99/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3676.0935 - mae: 3676.0935
Epoch 100/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3578.1790 - mae: 3578.1790
Epoch 101/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3659.9050 - mae: 3659.9050
Epoch 102/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3680.2561 - mae: 3680.2561
Epoch 103/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3580.7256 - mae: 3580.7256
Epoch 104/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3548.0876 - mae: 3548.0876
Epoch 105/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3629.3643 - mae: 3629.3643
Epoch 106/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3571.6694 - mae: 3571.6694
Epoch 107/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3543.7424 - mae: 3543.7424
Epoch 108/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3705.2893 - mae: 3705.2893
Epoch 109/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3603.0515 - mae: 3603.0515
Epoch 110/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3603.3538 - mae: 3603.3538
Epoch 111/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3651.2249 - mae: 3651.2249
Epoch 112/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3585.3162 - mae: 3585.3162
Epoch 113/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3565.2505 - mae: 3565.2505
Epoch 114/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3522.1052 - mae: 3522.1052
Epoch 115/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3634.9807 - mae: 3634.9807
Epoch 116/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3637.3025 - mae: 3637.3025
Epoch 117/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3585.2219 - mae: 3585.2219
Epoch 118/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3569.8137 - mae: 3569.8137
Epoch 119/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3575.9875 - mae: 3575.9875
Epoch 120/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3552.1843 - mae: 3552.1843
Epoch 121/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3686.4558 - mae: 3686.4558
Epoch 122/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3576.0515 - mae: 3576.0515
Epoch 123/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3645.7690 - mae: 3645.7690
Epoch 124/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3701.6143 - mae: 3701.6143
Epoch 125/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3582.2720 - mae: 3582.2720
Epoch 126/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3592.0010 - mae: 3592.0010
Epoch 127/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3551.9634 - mae: 3551.9634
Epoch 128/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3606.8875 - mae: 3606.8875
Epoch 129/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3549.8882 - mae: 3549.8882
Epoch 130/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3557.3625 - mae: 3557.3625
Epoch 131/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3592.5857 - mae: 3592.5857
Epoch 132/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3532.2439 - mae: 3532.2439
Epoch 133/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3528.5254 - mae: 3528.5254
Epoch 134/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3555.8328 - mae: 3555.8328
Epoch 135/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3624.6897 - mae: 3624.6897
Epoch 136/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3622.7029 - mae: 3622.7029
Epoch 137/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3700.2942 - mae: 3700.2942
Epoch 138/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3606.9856 - mae: 3606.9856
Epoch 139/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3540.0063 - mae: 3540.0063
Epoch 140/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3543.9858 - mae: 3543.9858
Epoch 141/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3540.6477 - mae: 3540.6477
Epoch 142/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3533.7759 - mae: 3533.7759
Epoch 143/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3659.3577 - mae: 3659.3577
Epoch 144/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3602.7349 - mae: 3602.7349
Epoch 145/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3526.8882 - mae: 3526.8882
Epoch 146/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3552.2681 - mae: 3552.2681
Epoch 147/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3626.9937 - mae: 3626.9937
Epoch 148/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3567.2192 - mae: 3567.2192
Epoch 149/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3531.9924 - mae: 3531.9924
Epoch 150/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3553.3613 - mae: 3553.3613
Epoch 151/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3536.2095 - mae: 3536.2095
Epoch 152/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3571.3867 - mae: 3571.3867
Epoch 153/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3570.6624 - mae: 3570.6624
Epoch 154/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3525.8879 - mae: 3525.8879
Epoch 155/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3605.5459 - mae: 3605.5459
Epoch 156/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3655.6023 - mae: 3655.6023
Epoch 157/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3565.4893 - mae: 3565.4893
Epoch 158/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3600.1912 - mae: 3600.1912
Epoch 159/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3540.0051 - mae: 3540.0051
Epoch 160/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3644.5969 - mae: 3644.5969
Epoch 161/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3588.0515 - mae: 3588.0515
Epoch 162/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3568.9561 - mae: 3568.9561
Epoch 163/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3565.0542 - mae: 3565.0542
Epoch 164/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3885.6069 - mae: 3885.6069
Epoch 165/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3727.1462 - mae: 3727.1462
Epoch 166/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3638.1406 - mae: 3638.1406
Epoch 167/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3622.3083 - mae: 3622.3083
Epoch 168/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3556.9326 - mae: 3556.9326
Epoch 169/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3551.4045 - mae: 3551.4045
Epoch 170/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3602.8589 - mae: 3602.8589
Epoch 171/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3515.3789 - mae: 3515.3789
Epoch 172/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3557.0190 - mae: 3557.0190
Epoch 173/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3596.4617 - mae: 3596.4617
Epoch 174/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3608.1121 - mae: 3608.1121
Epoch 175/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3759.8235 - mae: 3759.8235
Epoch 176/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3700.2341 - mae: 3700.2341
Epoch 177/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3637.3245 - mae: 3637.3245
Epoch 178/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3532.5547 - mae: 3532.5547
Epoch 179/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3582.8975 - mae: 3582.8975
Epoch 180/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3545.8323 - mae: 3545.8323
Epoch 181/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3584.4885 - mae: 3584.4885
Epoch 182/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3574.7581 - mae: 3574.7581
Epoch 183/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3619.4199 - mae: 3619.4199
Epoch 184/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3536.5234 - mae: 3536.5234
Epoch 185/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3644.6099 - mae: 3644.6099
Epoch 186/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3518.3879 - mae: 3518.3879
Epoch 187/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3618.9097 - mae: 3618.9097
Epoch 188/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3605.3779 - mae: 3605.3779
Epoch 189/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3549.5515 - mae: 3549.5515
Epoch 190/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3603.7107 - mae: 3603.7107
Epoch 191/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3613.0542 - mae: 3613.0542
Epoch 192/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3727.4976 - mae: 3727.4976
Epoch 193/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3586.7356 - mae: 3586.7356
Epoch 194/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3541.4294 - mae: 3541.4294
Epoch 195/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3552.8665 - mae: 3552.8665
Epoch 196/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3560.6301 - mae: 3560.6301
Epoch 197/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3546.7737 - mae: 3546.7737
Epoch 198/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3573.7891 - mae: 3573.7891
Epoch 199/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3717.7180 - mae: 3717.7180
Epoch 200/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3587.9204 - mae: 3587.9204
Epoch 201/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3564.6743 - mae: 3564.6743
Epoch 202/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3570.4070 - mae: 3570.4070
Epoch 203/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3624.0005 - mae: 3624.0005
Epoch 204/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3594.1987 - mae: 3594.1987
Epoch 205/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3537.5752 - mae: 3537.5752
Epoch 206/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3525.0408 - mae: 3525.0408
Epoch 207/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3535.3201 - mae: 3535.3201
Epoch 208/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3546.6204 - mae: 3546.6204
Epoch 209/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3576.7903 - mae: 3576.7903
Epoch 210/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3585.2639 - mae: 3585.2639
Epoch 211/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3584.1191 - mae: 3584.1191
Epoch 212/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3542.1045 - mae: 3542.1045
Epoch 213/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3546.1672 - mae: 3546.1672
Epoch 214/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3664.8989 - mae: 3664.8989
Epoch 215/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3658.3787 - mae: 3658.3787
Epoch 216/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3572.4368 - mae: 3572.4368
Epoch 217/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3560.8645 - mae: 3560.8645
Epoch 218/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3634.4302 - mae: 3634.4302
Epoch 219/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3700.7712 - mae: 3700.7712
Epoch 220/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3567.9324 - mae: 3567.9324
Epoch 221/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3551.4519 - mae: 3551.4519
Epoch 222/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3564.9146 - mae: 3564.9146
Epoch 223/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3614.5215 - mae: 3614.5215
Epoch 224/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3576.8701 - mae: 3576.8701
Epoch 225/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3568.2146 - mae: 3568.2146
Epoch 226/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3685.0645 - mae: 3685.0645
Epoch 227/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3607.4939 - mae: 3607.4939
Epoch 228/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3576.6599 - mae: 3576.6599
Epoch 229/300

In [ ]:
import numpy as np

y_preds = insurance_model1.predict(X_test)

y_test = np.array(y_test)

y_preds, y_test

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

(array([[10383.495  ],
        [ 9141.993  ],
        [10923.545  ],
        [ 7950.5923 ],
        [ 9304.092  ],
        [ 9506.846  ],
        [ 1143.608  ],
        [ 2803.535  ],
        [34728.652  ],
        [ 3029.9175 ],
        [ 5533.3955 ],
        [ 2959.7456 ],
        [ 1599.7382 ],
        [35598.61   ],
        [11038.495  ],
        [ 7707.109  ],
        [ 1737.0138 ],
        [ 9461.397  ],
        [ 5488.7085 ],
        [10747.59   ],
        [31384.697  ],
        [ 2881.4998 ],
        [ 5830.354  ],
        [ 1870.3439 ],
        [30017.904  ],
        [11049.487  ],
        [ 9078.423  ],
        [ 8042.463  ],
        [11231.791  ],
        [ 1904.1741 ],
        [12358.201  ],
        [29757.674  ],
        [ 1672.8706 ],
        [ 9306.069  ],
        [ 8533.843  ],
        [12586.841  ],
        [ 5893.3906 ],
        [ 5283.029  ],
        [ 5460.832  ],
        [10125.328  ],
        [11629.141  ],
        [37085.18   ],
        [  141.55878],
        [41734.973  ],
        [ 9230.618  ],
        [37277.22   ],
        [ 5623.3438 ],
        [37118.812  ],
        [41061.234  ],
        [10298.396  ],
        [30201.092  ],
        [11648.639  ],
        [11941.111  ],
        [ 1284.7316 ],
        [11122.566  ],
        [  761.97516],
        [38542.188  ],
        [ 7868.11   ],
        [ 9347.784  ],
        [ 8982.522  ],
        [37031.375  ],
        [38612.89   ],
        [ 7927.3887 ],
        [12596.735  ],
        [10632.967  ],
        [11970.637  ],
        [ 5202.6685 ],
        [  890.3771 ],
        [ 2378.3782 ],
        [37022.477  ],
        [11333.262  ],
        [10927.847  ],
        [11237.329  ],
        [ 5541.894  ],
        [36621.418  ],
        [31466.87   ],
        [ 7346.2817 ],
        [ 3849.2195 ],
        [10627.654  ],
        [36899.02   ],
        [10294.89   ],
        [38208.664  ],
        [39478.395  ],
        [ 3166.335  ],
        [ 2094.5999 ],
        [ 4532.599  ],
        [ 2019.7124 ],
        [29804.889  ],
        [ 3448.0466 ],
        [  673.5077 ],
        [31051.576  ],
        [10007.09   ],
        [41019.895  ],
        [ 4944.6567 ],
        [41017.207  ],
        [12266.172  ],
        [ 4593.462  ],
        [34912.594  ],
        [32183.777  ],
        [ 6469.3047 ],
        [ 2353.1182 ],
        [35462.04   ],
        [ 6353.0566 ],
        [ 5063.716  ],
        [ 4154.424  ],
        [10540.345  ],
        [ 7281.254  ],
        [37934.297  ],
        [35966.336  ],
        [36121.703  ],
        [ 9030.343  ],
        [40957.133  ],
        [30125.87   ],
        [ 6108.861  ],
        [11870.272  ],
        [40417.87   ],
        [ 3338.75   ],
        [37390.086  ],
        [ 7825.2734 ],
        [13742.245  ],
        [41536.3    ],
        [10002.435  ],
        [ 8663.054  ],
        [ 1086.4154 ],
        [ 1441.8342 ],
        [ 3591.3884 ],
        [11538.411  ],
        [ 5716.353  ],
        [ 7784.511  ],
        [11470.421  ],
        [ 8697.171  ],
        [ 2066.8572 ],
        [37307.12   ],
        [ 3114.9172 ],
        [30253.121  ],
        [ 1481.6252 ],
        [ 1606.9802 ],
        [35566.34   ],
        [ 4551.945  ],
        [ 2566.605  ],
        [ 5707.86   ],
        [ 3765.5454 ],
        [ 7324.4917 ],
        [33163.7    ],
        [11919.694  ],
        [ 6088.672  ],
        [ 7200.919  ],
        [ 1148.6997 ],
        [ 9446.088  ],
        [34892.832  ],
        [10621.415  ],
        [ 9976.711  ],
        [  539.4036 ],
        [39648.14   ],
        [12538.201  ],
        [ 7876.8545 ],
        [33926.29   ],
        [ 6538.0215 ],
        [ 6604.932  ],
        [ 8074.8184 ],
        [32727.92   ],
        [ 1632.7036 ],
        [ 5406.771  ],
        [34850.297  ],
        [ 6708.107  ],
        [ 8683.53   ],
        [11998.527  ],
        [ 2669.7266 ],
        [ 9368.458  ],
        [ 9407.073  ],
        [10290.294  ],
        [30266.97   ],
        [42050.33   ],
        [31589.217  ],
        [ 7661.4575 ],
        [ 3628.928  ],
        [11927.73   ],
        [12217.016  ],
        [  784.6491 ],
        [30471.785  ],
        [  652.4709 ],
        [39544.07   ],
        [ 7365.5776 ],
        [ 3401.1482 ],
        [ 4316.317  ],
        [ 6445.911  ],
        [ 3236.8088 ],
        [ 4356.074  ],
        [ 1862.6517 ],
        [ 9921.609  ],
        [11211.893  ],
        [ 9630.479  ],
        [ 9485.747  ],
        [13123.323  ],
        [29991.805  ],
        [13803.774  ],
        [ 3918.5857 ],
        [ 5159.2944 ],
        [10985.005  ],
        [ 5693.1177 ],
        [31883.22   ],
        [ 6278.774  ],
        [11303.272  ],
        [ 6970.415  ],
        [ 9592.69   ],
        [ 7848.8354 ],
        [ 1426.1766 ],
        [ 6437.353  ],
        [ 5260.0503 ],
        [33119.977  ],
        [31458.744  ],
        [32657.225  ],
        [10347.294  ],
        [ 5099.186  ],
        [40551.     ],
        [ 8429.432  ],
        [ 4167.0103 ],
        [ 7497.5894 ],
        [ 8656.621  ],
        [11611.427  ],
        [ 1555.5972 ],
        [10941.085  ],
        [ 6727.377  ],
        [ 9653.903  ],
        [ 4547.561  ],
        [11534.438  ],
        [ 5068.2188 ],
        [ 3204.4414 ],
        [ 5689.5356 ],
        [40945.92   ],
        [ 6757.1265 ],
        [ 7721.0522 ],
        [ 7925.427  ],
        [32159.65   ],
        [ 4895.886  ],
        [ 4675.611  ],
        [ 4144.8154 ],
        [ 4763.7876 ],
        [ 7687.635  ],
        [14198.357  ],
        [ 6912.8774 ],
        [ 1777.7944 ],
        [11887.956  ],
        [ 5186.6978 ],
        [34891.45   ],
        [ 9647.388  ],
        [ 4395.6685 ],
        [ 4155.7197 ],
        [ 2004.1029 ],
        [ 3653.5972 ],
        [ 6597.987  ],
        [10698.479  ],
        [36544.42   ],
        [ 7185.394  ],
        [ 1166.5464 ],
        [34402.016  ],
        [ 4046.469  ],
        [29575.31   ],
        [ 8539.085  ],
        [ 4412.03   ],
        [ 8256.623  ],
        [37710.91   ],
        [32293.896  ],
        [11209.032  ],
        [ 4235.64   ],
        [40669.805  ],
        [ 9012.948  ],
        [ 2076.6646 ]], dtype=float32),
 array([20630.28351,  8988.15875, 12094.478  ,  7345.084  ,  9377.9047 ,
         9861.025  ,  1842.519  ,  2322.6218 , 21472.4788 ,  3206.49135,
         5385.3379 , 14426.07385,  2130.6759 , 37829.7242 , 11735.87905,
         7160.3303 ,  2207.69745, 10065.413  ,  5327.40025, 12032.326  ,
        14571.8908 ,  2902.9065 ,  5272.1758 ,  2138.0707 , 33750.2918 ,
        11033.6617 ,  9222.4026 ,  8252.2843 , 12146.971  ,  2020.177  ,
        14349.8544 , 20167.33603,  2710.82855,  8823.98575,  8240.5896 ,
        13063.883  ,  5855.9025 ,  4320.41085,  4646.759  , 10422.91665,
        24227.33724, 42983.4585 ,  1121.8739 , 30942.1918 ,  9249.4952 ,
        40941.2854 ,  5148.5526 , 42124.5153 , 28101.33305, 10942.13205,
        38792.6856 , 13012.20865, 12730.9996 ,  1633.0444 , 11881.358  ,
         1253.936  , 23244.7902 ,  7441.053  ,  8798.593  ,  8871.1517 ,
        41034.2214 , 23967.38305,  7371.772  , 13228.84695, 10579.711  ,
        13047.33235,  5325.651  ,  1737.376  ,  2730.10785, 43896.3763 ,
        11743.9341 , 11741.726  , 12233.828  ,  4795.6568 , 48885.13561,
        17942.106  ,  6875.961  ,  3554.203  , 11520.09985, 21880.82   ,
        23045.56616, 46151.1245 , 42303.69215,  3561.8889 ,  2217.46915,
         4137.5227 ,  1917.3184 , 26125.67477,  2689.4954 ,  1625.43375,
        37165.1638 , 10214.636  , 47403.88   ,  4922.9159 , 47496.49445,
        13429.0354 ,  4433.3877 , 37701.8768 , 37133.8982 ,  6799.458  ,
         2254.7967 , 39047.285  ,  5976.8311 ,  4399.731  ,  3766.8838 ,
        10806.839  ,  6775.961  , 23401.30575, 41949.2441 , 19964.7463 ,
         8968.33   , 27037.9141 , 34303.1672 ,  6113.23105, 12913.9924 ,
        45008.9555 ,  3070.8087 , 40974.1649 ,  6610.1097 , 15170.069  ,
        48824.45   , 10493.9458 ,  9193.8385 ,  2304.0022 ,  1646.4297 ,
         4391.652  , 24513.09126,  5227.98875,  7160.094  , 11396.9002 ,
         8522.003  ,  2026.9741 , 39725.51805, 18218.16139, 33307.5508 ,
         1880.07   , 21595.38229, 38245.59327,  4438.2634 ,  2523.1695 ,
         4536.259  ,  2927.0647 ,  7147.105  , 17361.7661 , 12643.3778 ,
         5377.4578 ,  6858.4796 ,  1149.3959 ,  9283.562  , 20773.62775,
        11253.421  , 10791.96   ,  1727.785  , 63770.42801, 13224.05705,
         7441.501  , 18765.87545,  5969.723  ,  6250.435  ,  8605.3615 ,
        16115.3045 ,  1980.07   ,  4889.0368 , 39871.7043 ,  6082.405  ,
         8068.185  , 12485.8009 , 12609.88702,  8964.06055,  9048.0273 ,
        10461.9794 , 17178.6824 , 47305.305  , 34254.05335,  7418.522  ,
         3172.018  , 30063.58055, 12982.8747 ,  1628.4709 , 17560.37975,
         1615.7667 , 43921.1837 ,  6435.6237 ,  3260.199  ,  4349.462  ,
         6203.90175,  2866.091  ,  4185.0979 ,  2211.13075,  9778.3472 ,
        11840.77505,  9411.005  ,  9620.3307 , 14692.66935, 34439.8559 ,
        15612.19335,  3756.6216 ,  4746.344  , 12142.5786 ,  4686.3887 ,
        34672.1472 ,  5729.0053 , 12129.61415,  6748.5912 , 10156.7832 ,
         8582.3023 ,  2585.269  ,  5400.9805 ,  5152.134  , 16657.71745,
        35147.52848, 40904.1995 , 10226.2842 ,  4747.0529 , 48173.361  ,
         8516.829  ,  4827.90495,  7512.267  ,  7804.1605 , 12268.63225,
        11272.33139, 10959.6947 ,  6389.37785,  9724.53   , 17128.42608,
        11879.10405,  4462.7218 ,  3227.1211 ,  5240.765  , 28868.6639 ,
         6338.0756 ,  7624.63   ,  7265.7025 , 39611.7577 ,  4571.41305,
        19442.3535 ,  3471.4096 ,  4454.40265,  7419.4779 , 16069.08475,
         6360.9936 ,  2154.361  , 30259.99556, 24671.66334, 38415.474  ,
         9630.397  ,  4040.55825,  4058.71245, 25081.76784,  4189.1131 ,
         6933.24225, 11305.93455, 40003.33225,  7045.499  ,  1391.5287 ,
        16776.30405,  4504.6624 , 13747.87235, 12797.20962,  4239.89265,
         7639.41745, 42969.8527 , 19933.458  , 11658.37915, 23288.9284 ,
        48970.2476 ,  9095.06825,  1682.597  ]))

## Import the Boston pricing dataset from TensorFlow tf.keras.datasets and model it.

In [ ]:
BostonHouses = tf.keras.datasets.boston_housing


(X_train, y_train), (X_test, y_test) = BostonHouses.load_data()

def buid_model():
  model = tf.keras.Sequential([
      tf.keras.layers.Dense(1)
  ])
  model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.1),
                 loss=tf.keras.losses.mae,
                 metrics=["mae"])
  return model


model2 = buid_model()
model2.fit(X_train, y_train, epochs=200)

Epoch 1/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 38.3539 - mae: 38.3539
Epoch 2/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16.5248 - mae: 16.5248
Epoch 3/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.2617 - mae: 11.2617
Epoch 4/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.3494 - mae: 11.3494
Epoch 5/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.5223 - mae: 7.5223
Epoch 6/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.5973 - mae: 6.5973
Epoch 7/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.0592 - mae: 6.0592
Epoch 8/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.9016 - mae: 6.9016
Epoch 9/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2362 - mae: 7.2362
Epoch 10/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.5506 - mae: 7.5506
Epoch 11/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.6744 - mae: 6.6744
Epoch 12/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.7890 - mae: 5.7890
Epoch 13/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.2657 - mae: 5.2657
Epoch 14/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.6166 - mae: 6.6166
Epoch 15/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.9086 - mae: 9.9086
Epoch 16/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.0799 - mae: 13.0799
Epoch 17/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.2845 - mae: 9.2845
Epoch 18/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.0758 - mae: 5.0758
Epoch 19/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.8781 - mae: 4.8781
Epoch 20/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.1573 - mae: 5.1573
Epoch 21/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2069 - mae: 7.2069
Epoch 22/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.2381 - mae: 8.2381
Epoch 23/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.8858 - mae: 6.8858
Epoch 24/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.7338 - mae: 7.7338
Epoch 25/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.4386 - mae: 6.4386
Epoch 26/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.6942 - mae: 5.6942
Epoch 27/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.3201 - mae: 7.3201
Epoch 28/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.5152 - mae: 4.5152
Epoch 29/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.7408 - mae: 5.7408
Epoch 30/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.6554 - mae: 10.6554
Epoch 31/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.4121 - mae: 9.4121
Epoch 32/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.3765 - mae: 7.3765
Epoch 33/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.4400 - mae: 6.4400
Epoch 34/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.0300 - mae: 7.0300
Epoch 35/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.6703 - mae: 8.6703
Epoch 36/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.1673 - mae: 8.1673
Epoch 37/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1008 - mae: 6.1008
Epoch 38/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.0780 - mae: 5.0780
Epoch 39/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.1829 - mae: 4.1829
Epoch 40/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.4249 - mae: 4.4249
Epoch 41/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.3501 - mae: 5.3501
Epoch 42/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.4615 - mae: 6.4615
Epoch 43/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2728 - mae: 7.2728
Epoch 44/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.6372 - mae: 7.6372
Epoch 45/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.4726 - mae: 11.4726
Epoch 46/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.9842 - mae: 8.9842
Epoch 47/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.5850 - mae: 7.5850
Epoch 48/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3583 - mae: 6.3583
Epoch 49/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.4494 - mae: 10.4494
Epoch 50/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.8772 - mae: 10.8772
Epoch 51/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.9476 - mae: 11.9476
Epoch 52/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.8467 - mae: 7.8467
Epoch 53/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.9291 - mae: 6.9291
Epoch 54/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.3988 - mae: 5.3988
Epoch 55/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4.7302 - mae: 4.7302
Epoch 56/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4703 - mae: 6.4703
Epoch 57/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.3540 - mae: 7.3540
Epoch 58/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4.5212 - mae: 4.5212
Epoch 59/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4.1426 - mae: 4.1426
Epoch 60/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.3210 - mae: 4.3210
Epoch 61/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4.4756 - mae: 4.4756
Epoch 62/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9990 - mae: 5.9990
Epoch 63/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4.3667 - mae: 4.3667
Epoch 64/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4.5931 - mae: 4.5931
Epoch 65/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.7632 - mae: 7.7632
Epoch 66/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.5048 - mae: 7.5048
Epoch 67/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.1594 - mae: 6.1594
Epoch 68/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.1676 - mae: 7.1676
Epoch 69/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.1666 - mae: 7.1666
Epoch 70/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.3465 - mae: 5.3465
Epoch 71/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.0721 - mae: 4.0721
Epoch 72/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3.7582 - mae: 3.7582
Epoch 73/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.4545 - mae: 5.4545
Epoch 74/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.4412 - mae: 8.4412
Epoch 75/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.5924 - mae: 11.5924
Epoch 76/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.8438 - mae: 7.8438
Epoch 77/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.6931 - mae: 4.6931
Epoch 78/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.5186 - mae: 4.5186
Epoch 79/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.2929 - mae: 10.2929
Epoch 80/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.0445 - mae: 9.0445
Epoch 81/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.3752 - mae: 7.3752
Epoch 82/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.9914 - mae: 5.9914
Epoch 83/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.6173 - mae: 6.6173
Epoch 84/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.7514 - mae: 6.7514
Epoch 85/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.8655 - mae: 4.8655
Epoch 86/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.9421 - mae: 5.9421
Epoch 87/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.9982 - mae: 10.9982
Epoch 88/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.8732 - mae: 8.8732
Epoch 89/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.3182 - mae: 8.3182
Epoch 90/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.0696 - mae: 6.0696
Epoch 91/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.7502 - mae: 5.7502
Epoch 92/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.3789 - mae: 8.3789
Epoch 93/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.6255 - mae: 7.6255
Epoch 94/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.6814 - mae: 6.6814
Epoch 95/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.8507 - mae: 4.8507
Epoch 96/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.8973 - mae: 4.8973
Epoch 97/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.4421 - mae: 4.4421
Epoch 98/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.6846 - mae: 6.6846
Epoch 99/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.5103 - mae: 6.5103
Epoch 100/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.5107 - mae: 4.5107
Epoch 101/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.7307 - mae: 8.7307
Epoch 102/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.6922 - mae: 6.6922
Epoch 103/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1023 - mae: 6.1023
Epoch 104/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.2725 - mae: 4.2725
Epoch 105/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.3209 - mae: 4.3209
Epoch 106/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.8576 - mae: 6.8576
Epoch 107/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.4157 - mae: 6.4157
Epoch 108/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.3989 - mae: 7.3989
Epoch 109/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3696 - mae: 6.3696
Epoch 110/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.6456 - mae: 4.6456
Epoch 111/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.7983 - mae: 4.7983
Epoch 112/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2473 - mae: 6.2473
Epoch 113/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.6932 - mae: 6.6932
Epoch 114/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.5833 - mae: 11.5833
Epoch 115/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.6209 - mae: 8.6209
Epoch 116/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.0629 - mae: 7.0629
Epoch 117/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.0338 - mae: 7.0338
Epoch 118/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.1701 - mae: 11.1701
Epoch 119/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.9216 - mae: 5.9216
Epoch 120/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.3361 - mae: 7.3361
Epoch 121/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.8766 - mae: 4.8766
Epoch 122/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3.9628 - mae: 3.9628
Epoch 123/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.8083 - mae: 6.8083
Epoch 124/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.0470 - mae: 5.0470
Epoch 125/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.0876 - mae: 4.0876
Epoch 126/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.6778 - mae: 5.6778
Epoch 127/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.5535 - mae: 7.5535
Epoch 128/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.8232 - mae: 6.8232
Epoch 129/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.5367 - mae: 4.5367
Epoch 130/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.0571 - mae: 4.0571
Epoch 131/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.1941 - mae: 5.1941
Epoch 132/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.3242 - mae: 4.3242
Epoch 133/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.6252 - mae: 4.6252
Epoch 134/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.8314 - mae: 6.8314
Epoch 135/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.9121 - mae: 5.9121
Epoch 136/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2228 - mae: 6.2228
Epoch 137/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.1051 - mae: 9.1051
Epoch 138/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.7044 - mae: 9.7044
Epoch 139/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3615 - mae: 6.3615
Epoch 140/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.8676 - mae: 6.8676
Epoch 141/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.5738 - mae: 4.5738
Epoch 142/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2985 - mae: 6.2985
Epoch 143/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.2921 - mae: 10.2921
Epoch 144/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.4907 - mae: 6.4907
Epoch 145/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.6113 - mae: 5.6113
Epoch 146/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.6938 - mae: 6.6938
Epoch 147/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.3485 - mae: 10.3485
Epoch 148/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16.2080 - mae: 16.2080
Epoch 149/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.2872 - mae: 17.2872
Epoch 150/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.1050 - mae: 11.1050
Epoch 151/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.9752 - mae: 9.9752
Epoch 152/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.0112 - mae: 9.0112
Epoch 153/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.5087 - mae: 7.5087
Epoch 154/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.9083 - mae: 6.9083
Epoch 155/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.0288 - mae: 7.0288
Epoch 156/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.8466 - mae: 5.8466
Epoch 157/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9182 - mae: 7.9182
Epoch 158/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2995 - mae: 7.2995
Epoch 159/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.0868 - mae: 5.0868
Epoch 160/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.7971 - mae: 4.7971
Epoch 161/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.8817 - mae: 4.8817
Epoch 162/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.3073 - mae: 4.3073
Epoch 163/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3.9462 - mae: 3.9462
Epoch 164/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.7764 - mae: 5.7764
Epoch 165/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.4559 - mae: 7.4559
Epoch 166/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.6873 - mae: 4.6873
Epoch 167/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3850 - mae: 9.3850
Epoch 168/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.5446 - mae: 11.5446
Epoch 169/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.4291 - mae: 11.4291
Epoch 170/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.9338 - mae: 8.9338
Epoch 171/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.5933 - mae: 11.5933
Epoch 172/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.9005 - mae: 4.9005
Epoch 173/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.9667 - mae: 4.9667
Epoch 174/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.5335 - mae: 5.5335
Epoch 175/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.5430 - mae: 4.5430
Epoch 176/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.0946 - mae: 7.0946
Epoch 177/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3623 - mae: 6.3623
Epoch 178/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3328 - mae: 6.3328
Epoch 179/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3.8972 - mae: 3.8972
Epoch 180/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.5617 - mae: 4.5617
Epoch 181/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.4496 - mae: 5.4496
Epoch 182/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.1774 - mae: 5.1774
Epoch 183/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.3796 - mae: 5.3796
Epoch 184/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3.8507 - mae: 3.8507
Epoch 185/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.2876 - mae: 5.2876
Epoch 186/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.5130 - mae: 4.5130
Epoch 187/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3.7510 - mae: 3.7510
Epoch 188/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3.9941 - mae: 3.9941
Epoch 189/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3.7729 - mae: 3.7729
Epoch 190/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.0590 - mae: 4.0590
Epoch 191/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.7330 - mae: 4.7330
Epoch 192/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.5780 - mae: 6.5780
Epoch 193/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.0657 - mae: 4.0657
Epoch 194/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.2649 - mae: 4.2649
Epoch 195/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.9682 - mae: 6.9682
Epoch 196/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.0089 - mae: 10.0089
Epoch 197/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.7996 - mae: 7.7996
Epoch 198/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2206 - mae: 7.2206
Epoch 199/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.0988 - mae: 7.0988
Epoch 200/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.6516 - mae: 5.6516

In [ ]:
# Evaluate
model1.evaluate(X_test, y_test)