<a href="https://colab.research.google.com/github/Glockrover/LearnTensorFlow/blob/main/Exercises/01_NeuralNetwork_excercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🛠 01. Neural network regression with TensorFlow Exercises

1. Create your own regression dataset (or make the one we created in "Create data to view and fit" bigger) and build fit a model to it.

2. Try building a neural network with 4 Dense layers and fitting it to your own regression dataset, how does it perform?

3. Try and improve the results we got on the insurance dataset, some things you might want to try include:
  * Building a larger model (how does one with 4 dense layers go?).
  * Increasing the number of units in each layer.
  * Lookup the documentation of Adam and find out what the first parameter is, what happens if you increase it by 10x?
  * What happens if you train for longer (say 300 epochs instead of 200)?
  
4. Import the Boston pricing dataset from TensorFlow tf.keras.datasets and model it.

## 📖 01. Neural network regression with TensorFlow Extra-curriculum

* [MIT introduction deep learning lecture 1](https://www.youtube.com/watch?v=7sB052Pz0sQ&ab_channel=AlexanderAmini) - gives a great overview of what's happening behind all of the code we're running.

* Reading: 1-hour of [Chapter 1 of Neural Networks and Deep Learning](http://neuralnetworksanddeeplearning.com/chap1.html) by Michael Nielson - a great in-depth and hands-on example of the intuition behind neural networks.

* To practice your regression modelling with TensorFlow, I'd also encourage you to look through [Kaggle's datasets](https://www.kaggle.com/data), find a regression dataset which sparks your interest and try to model.

## 1. Creating our own data set

We are going to use a simple yet powerful way of seeing if our deep learing model works.
The equation is simple `f(x) = 2x`.
![Equation](https://substackcdn.com/image/fetch/$s_!IeZt!,w_1200,h_675,c_fill,f_jpg,q_auto:good,fl_progressive:steep,g_auto/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fc0070a50-7da3-43bb-903c-8249d7d08dcb_1600x608.jpeg)

In [1]:
# First we going to create the dataset
X = [n for n in range(1000)]
y = [n * 2 for n in range(1000)]

In [2]:
import tensorflow as tf

X = tf.constant(tf.expand_dims(X, axis=-1))
y = tf.constant(tf.expand_dims(y, axis=-1))

# Creating our model
model1 = tf.keras.Sequential([
    tf.keras.layers.Dense(1),

])

# Compile the model
model1.compile(loss=tf.losses.mae,
               optimizer=tf.optimizers.SGD(),
               metrics=["mae"])

# Fitting the model
model1.fit(X, y, epochs=200)

Epoch 1/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1252.6643 - mae: 1252.6643
Epoch 2/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1243.2942 - mae: 1243.2942
Epoch 3/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1249.2687 - mae: 1249.2687
Epoch 4/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1248.5759 - mae: 1248.5759
Epoch 5/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1293.5952 - mae: 1293.5952
Epoch 6/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1248.9048 - mae: 1248.9048
Epoch 7/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1307.2440 - mae: 1307.2440
Epoch 8/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1266.0785 - mae: 1266.0785
Epoch 9/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1261.2263 - mae: 1261.2263
Epoch 10/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1272.6178 - mae: 1272.6178
Epoch 11/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1258.4208 - mae: 1258.4208
Epoch 12/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1284.9473 - mae: 1284.9473
Epoch 13/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1249.4364 - mae: 1249.4364
Epoch 14/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1254.5398 - mae: 1254.5398
Epoch 15/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1265.7393 - mae: 1265.7393
Epoch 16/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1240.6460 - mae: 1240.6460
Epoch 17/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1264.4359 - mae: 1264.4359
Epoch 18/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1255.2037 - mae: 1255.2037
Epoch 19/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1265.7987 - mae: 1265.7987
Epoch 20/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1259.4027 - mae: 1259.4027
Epoch 21/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1257.3143 - mae: 1257.3143
Epoch 22/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1277.1475 - mae: 1277.1475
Epoch 23/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1299.2812 - mae: 1299.2812
Epoch 24/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1266.0570 - mae: 1266.0570
Epoch 25/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1309.3772 - mae: 1309.3772
Epoch 26/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1288.1008 - mae: 1288.1008
Epoch 27/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1272.4247 - mae: 1272.4247
Epoch 28/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1276.6887 - mae: 1276.6887
Epoch 29/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1284.8447 - mae: 1284.8447
Epoch 30/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1249.1281 - mae: 1249.1281
Epoch 31/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1249.5719 - mae: 1249.5719
Epoch 32/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1237.0074 - mae: 1237.0074
Epoch 33/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1341.0067 - mae: 1341.0067
Epoch 34/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1252.5647 - mae: 1252.5647
Epoch 35/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1248.6030 - mae: 1248.6030
Epoch 36/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1300.0081 - mae: 1300.0081
Epoch 37/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1252.2650 - mae: 1252.2650
Epoch 38/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1283.5525 - mae: 1283.5525
Epoch 39/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1238.0901 - mae: 1238.0901
Epoch 40/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1256.3279 - mae: 1256.3279
Epoch 41/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1282.5051 - mae: 1282.5051
Epoch 42/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1250.5580 - mae: 1250.5580
Epoch 43/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1298.0348 - mae: 1298.0348
Epoch 44/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1250.1532 - mae: 1250.1532
Epoch 45/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1244.8325 - mae: 1244.8325
Epoch 46/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1243.6553 - mae: 1243.6553
Epoch 47/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1239.8517 - mae: 1239.8517
Epoch 48/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1247.5076 - mae: 1247.5076
Epoch 49/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1254.9579 - mae: 1254.9579
Epoch 50/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1311.5294 - mae: 1311.5294
Epoch 51/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1263.3676 - mae: 1263.3676
Epoch 52/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1251.8979 - mae: 1251.8979
Epoch 53/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1250.6973 - mae: 1250.6973
Epoch 54/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1248.7278 - mae: 1248.7278
Epoch 55/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1249.3884 - mae: 1249.3884
Epoch 56/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1253.4188 - mae: 1253.4188
Epoch 57/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1287.3280 - mae: 1287.3280
Epoch 58/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1289.5377 - mae: 1289.5377
Epoch 59/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1279.8008 - mae: 1279.8008
Epoch 60/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1294.3599 - mae: 1294.3599
Epoch 61/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1254.0061 - mae: 1254.0061
Epoch 62/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1264.1180 - mae: 1264.1180
Epoch 63/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1287.1263 - mae: 1287.1263
Epoch 64/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1275.1263 - mae: 1275.1263
Epoch 65/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1238.2240 - mae: 1238.2240
Epoch 66/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1259.0560 - mae: 1259.0560
Epoch 67/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1266.1879 - mae: 1266.1879
Epoch 68/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1271.0586 - mae: 1271.0586
Epoch 69/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1269.8041 - mae: 1269.8041
Epoch 70/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1275.8220 - mae: 1275.8220
Epoch 71/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1223.7788 - mae: 1223.7788
Epoch 72/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1233.2184 - mae: 1233.2184
Epoch 73/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1260.4847 - mae: 1260.4847
Epoch 74/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1240.8754 - mae: 1240.8754
Epoch 75/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1231.9512 - mae: 1231.9512
Epoch 76/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1255.8644 - mae: 1255.8644
Epoch 77/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1282.4904 - mae: 1282.4904
Epoch 78/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1239.8021 - mae: 1239.8021
Epoch 79/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1245.8365 - mae: 1245.8365
Epoch 80/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1259.3124 - mae: 1259.3124
Epoch 81/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1273.2760 - mae: 1273.2760
Epoch 82/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1269.7026 - mae: 1269.7026
Epoch 83/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1249.8784 - mae: 1249.8784
Epoch 84/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1247.9271 - mae: 1247.9271
Epoch 85/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1287.8834 - mae: 1287.8834
Epoch 86/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1239.0997 - mae: 1239.0997
Epoch 87/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1236.6611 - mae: 1236.6611
Epoch 88/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1264.8123 - mae: 1264.8123
Epoch 89/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1258.4562 - mae: 1258.4562
Epoch 90/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1241.8960 - mae: 1241.8960
Epoch 91/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1238.6794 - mae: 1238.6794
Epoch 92/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1237.4076 - mae: 1237.4076
Epoch 93/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1235.0483 - mae: 1235.0483
Epoch 94/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1251.8009 - mae: 1251.8009
Epoch 95/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1271.0397 - mae: 1271.0397
Epoch 96/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1249.5013 - mae: 1249.5013
Epoch 97/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1248.6830 - mae: 1248.6830
Epoch 98/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1257.2045 - mae: 1257.2045
Epoch 99/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1258.0582 - mae: 1258.0582
Epoch 100/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1237.3505 - mae: 1237.3505
Epoch 101/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1255.0844 - mae: 1255.0844
Epoch 102/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1262.0951 - mae: 1262.0951
Epoch 103/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1219.3408 - mae: 1219.3408
Epoch 104/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1245.3253 - mae: 1245.3253
Epoch 105/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1245.9208 - mae: 1245.9208
Epoch 106/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1255.2577 - mae: 1255.2577
Epoch 107/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1258.9928 - mae: 1258.9928
Epoch 108/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1278.8102 - mae: 1278.8102
Epoch 109/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1276.8693 - mae: 1276.8693
Epoch 110/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1306.2146 - mae: 1306.2146
Epoch 111/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1255.3175 - mae: 1255.3175
Epoch 112/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1251.4852 - mae: 1251.4852
Epoch 113/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1265.4027 - mae: 1265.4027
Epoch 114/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1279.5712 - mae: 1279.5712
Epoch 115/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1276.0059 - mae: 1276.0059
Epoch 116/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1273.5829 - mae: 1273.5829
Epoch 117/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1281.9220 - mae: 1281.9220
Epoch 118/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1272.3186 - mae: 1272.3186
Epoch 119/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1268.0750 - mae: 1268.0750
Epoch 120/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1275.4653 - mae: 1275.4653
Epoch 121/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1292.8938 - mae: 1292.8938
Epoch 122/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1250.0310 - mae: 1250.0310
Epoch 123/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1297.3936 - mae: 1297.3936
Epoch 124/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1275.8766 - mae: 1275.8766
Epoch 125/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1287.9360 - mae: 1287.9360
Epoch 126/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1252.9265 - mae: 1252.9265
Epoch 127/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1260.9097 - mae: 1260.9097
Epoch 128/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1275.7560 - mae: 1275.7560
Epoch 129/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1270.8785 - mae: 1270.8785
Epoch 130/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1246.7098 - mae: 1246.7098
Epoch 131/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1241.7832 - mae: 1241.7832
Epoch 132/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1245.3083 - mae: 1245.3083
Epoch 133/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1247.1465 - mae: 1247.1465
Epoch 134/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1269.4965 - mae: 1269.4965
Epoch 135/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1282.8114 - mae: 1282.8114
Epoch 136/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1246.1812 - mae: 1246.1812
Epoch 137/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1263.5460 - mae: 1263.5460
Epoch 138/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1244.2975 - mae: 1244.2975
Epoch 139/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1241.5425 - mae: 1241.5425
Epoch 140/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1334.8574 - mae: 1334.8574
Epoch 141/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1253.3427 - mae: 1253.3427
Epoch 142/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1294.7698 - mae: 1294.7698
Epoch 143/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1262.5640 - mae: 1262.5640
Epoch 144/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1243.5363 - mae: 1243.5363
Epoch 145/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1242.0840 - mae: 1242.0840
Epoch 146/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1261.2892 - mae: 1261.2892
Epoch 147/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1229.0105 - mae: 1229.0105
Epoch 148/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1251.1562 - mae: 1251.1562
Epoch 149/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1246.6593 - mae: 1246.6593
Epoch 150/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1262.7466 - mae: 1262.7466
Epoch 151/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1251.5621 - mae: 1251.5621
Epoch 152/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1257.5286 - mae: 1257.5286
Epoch 153/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1254.1516 - mae: 1254.1516
Epoch 154/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1240.0011 - mae: 1240.0011
Epoch 155/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1244.5874 - mae: 1244.5874
Epoch 156/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1263.9556 - mae: 1263.9556
Epoch 157/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1254.4476 - mae: 1254.4476
Epoch 158/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1268.3862 - mae: 1268.3862
Epoch 159/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1270.6757 - mae: 1270.6757
Epoch 160/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1296.7882 - mae: 1296.7882
Epoch 161/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1286.6417 - mae: 1286.6417
Epoch 162/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1302.0975 - mae: 1302.0975
Epoch 163/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1235.6996 - mae: 1235.6996
Epoch 164/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1271.1171 - mae: 1271.1171
Epoch 165/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1272.8308 - mae: 1272.8308
Epoch 166/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1266.7145 - mae: 1266.7145
Epoch 167/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1280.3229 - mae: 1280.3229
Epoch 168/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1254.1018 - mae: 1254.1018
Epoch 169/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1274.2714 - mae: 1274.2714
Epoch 170/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1224.8519 - mae: 1224.8519
Epoch 171/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1237.0527 - mae: 1237.0527
Epoch 172/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1235.7528 - mae: 1235.7528
Epoch 173/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1252.2830 - mae: 1252.2830
Epoch 174/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1273.5054 - mae: 1273.5054
Epoch 175/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1273.5637 - mae: 1273.5637
Epoch 176/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1274.3286 - mae: 1274.3286
Epoch 177/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1279.4706 - mae: 1279.4706
Epoch 178/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1260.7068 - mae: 1260.7068
Epoch 179/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1274.4897 - mae: 1274.4897
Epoch 180/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1268.5602 - mae: 1268.5602
Epoch 181/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1245.9320 - mae: 1245.9320
Epoch 182/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1251.2316 - mae: 1251.2316
Epoch 183/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1218.4952 - mae: 1218.4952
Epoch 184/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1254.0492 - mae: 1254.0492
Epoch 185/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1239.8792 - mae: 1239.8792
Epoch 186/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1239.1774 - mae: 1239.1774
Epoch 187/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1266.1941 - mae: 1266.1941
Epoch 188/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1260.0002 - mae: 1260.0002
Epoch 189/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1246.9375 - mae: 1246.9375
Epoch 190/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1274.6329 - mae: 1274.6329
Epoch 191/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1250.9003 - mae: 1250.9003
Epoch 192/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1241.6053 - mae: 1241.6053
Epoch 193/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1251.6814 - mae: 1251.6814
Epoch 194/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1275.0144 - mae: 1275.0144
Epoch 195/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1276.1572 - mae: 1276.1572
Epoch 196/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1303.4130 - mae: 1303.4130
Epoch 197/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1243.0170 - mae: 1243.0170
Epoch 198/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1256.8966 - mae: 1256.8966
Epoch 199/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1308.5635 - mae: 1308.5635
Epoch 200/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1271.5310 - mae: 1271.5310

In [3]:
# Predict the number from our model
input = tf.constant([1000])
input = tf.expand_dims(input, axis=-1)
model1.predict(input)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step

array([[352.8155]], dtype=float32)

## Try building a neural network with 4 Dense layers and fitting it to your own regression dataset, how does it perform?

In [4]:
# Creating our model
model2 = tf.keras.Sequential([
    tf.keras.layers.Dense(100, input_shape=(1,)),
    tf.keras.layers.Dense(50),
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1)

])

# Compile the model
model1.compile(loss=tf.losses.mae,
               optimizer=tf.optimizers.SGD(),
               metrics=["mae"])

# Fitting the model
model1.fit(X, y, epochs=200)

Epoch 1/200

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1227.6320 - mae: 1227.6320
Epoch 2/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1241.3606 - mae: 1241.3606
Epoch 3/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1232.7426 - mae: 1232.7426
Epoch 4/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1261.3641 - mae: 1261.3641
Epoch 5/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1283.6566 - mae: 1283.6566
Epoch 6/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1259.5405 - mae: 1259.5405
Epoch 7/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1258.4834 - mae: 1258.4834
Epoch 8/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1255.0402 - mae: 1255.0402
Epoch 9/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1259.3074 - mae: 1259.3074
Epoch 10/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1284.7893 - mae: 1284.7893
Epoch 11/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1255.7201 - mae: 1255.7201
Epoch 12/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1286.0045 - mae: 1286.0045
Epoch 13/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1297.2413 - mae: 1297.2413
Epoch 14/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1272.0969 - mae: 1272.0969
Epoch 15/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1262.3438 - mae: 1262.3438
Epoch 16/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1270.9525 - mae: 1270.9525
Epoch 17/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1239.2573 - mae: 1239.2573
Epoch 18/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1244.8018 - mae: 1244.8018
Epoch 19/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1239.1389 - mae: 1239.1389
Epoch 20/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1249.0031 - mae: 1249.0031
Epoch 21/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1260.3831 - mae: 1260.3831
Epoch 22/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1265.4135 - mae: 1265.4135
Epoch 23/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1251.6669 - mae: 1251.6669
Epoch 24/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1251.9393 - mae: 1251.9393
Epoch 25/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1276.8362 - mae: 1276.8362
Epoch 26/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1310.4225 - mae: 1310.4225
Epoch 27/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1266.6495 - mae: 1266.6495
Epoch 28/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1253.2031 - mae: 1253.2031
Epoch 29/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1236.0869 - mae: 1236.0869
Epoch 30/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1227.5605 - mae: 1227.5605
Epoch 31/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1252.1219 - mae: 1252.1219
Epoch 32/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1257.6472 - mae: 1257.6472
Epoch 33/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1294.3488 - mae: 1294.3488
Epoch 34/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1301.0319 - mae: 1301.0319
Epoch 35/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1294.8702 - mae: 1294.8702
Epoch 36/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1251.0591 - mae: 1251.0591
Epoch 37/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1280.3809 - mae: 1280.3809
Epoch 38/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1255.5491 - mae: 1255.5491
Epoch 39/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1260.5856 - mae: 1260.5856
Epoch 40/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1255.4781 - mae: 1255.4781
Epoch 41/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1251.2126 - mae: 1251.2126
Epoch 42/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1299.4594 - mae: 1299.4594
Epoch 43/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1275.2423 - mae: 1275.2423
Epoch 44/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1259.0464 - mae: 1259.0464
Epoch 45/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1281.8719 - mae: 1281.8719
Epoch 46/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1263.8748 - mae: 1263.8748
Epoch 47/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1319.6162 - mae: 1319.6162
Epoch 48/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1269.8586 - mae: 1269.8586
Epoch 49/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1277.4539 - mae: 1277.4539
Epoch 50/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1270.5184 - mae: 1270.5184
Epoch 51/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1278.8226 - mae: 1278.8226
Epoch 52/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1253.9222 - mae: 1253.9222
Epoch 53/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1260.6416 - mae: 1260.6416
Epoch 54/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1259.1700 - mae: 1259.1700
Epoch 55/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1227.5519 - mae: 1227.5519
Epoch 56/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1235.7140 - mae: 1235.7140
Epoch 57/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1252.2167 - mae: 1252.2167
Epoch 58/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1287.9208 - mae: 1287.9208
Epoch 59/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1235.9243 - mae: 1235.9243
Epoch 60/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1249.1752 - mae: 1249.1752
Epoch 61/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1259.0074 - mae: 1259.0074
Epoch 62/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1272.7675 - mae: 1272.7675
Epoch 63/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1256.9606 - mae: 1256.9606
Epoch 64/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1270.4921 - mae: 1270.4921
Epoch 65/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1255.9323 - mae: 1255.9323
Epoch 66/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1253.0227 - mae: 1253.0227
Epoch 67/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1267.3280 - mae: 1267.3280
Epoch 68/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1247.4291 - mae: 1247.4291
Epoch 69/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1262.5031 - mae: 1262.5031
Epoch 70/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1303.7791 - mae: 1303.7791
Epoch 71/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1254.6299 - mae: 1254.6299
Epoch 72/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1287.3551 - mae: 1287.3551
Epoch 73/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1268.3693 - mae: 1268.3693
Epoch 74/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1258.1045 - mae: 1258.1045
Epoch 75/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1242.0116 - mae: 1242.0116
Epoch 76/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1256.6096 - mae: 1256.6096
Epoch 77/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1254.7982 - mae: 1254.7982
Epoch 78/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1237.9867 - mae: 1237.9867
Epoch 79/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1257.2195 - mae: 1257.2195
Epoch 80/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1244.0806 - mae: 1244.0806
Epoch 81/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1252.5342 - mae: 1252.5342
Epoch 82/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1264.1962 - mae: 1264.1962
Epoch 83/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1252.6973 - mae: 1252.6973
Epoch 84/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1274.8680 - mae: 1274.8680
Epoch 85/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1276.8851 - mae: 1276.8851
Epoch 86/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1243.2814 - mae: 1243.2814
Epoch 87/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1252.2720 - mae: 1252.2720
Epoch 88/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1265.4296 - mae: 1265.4296
Epoch 89/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1248.9240 - mae: 1248.9240
Epoch 90/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1257.9343 - mae: 1257.9343
Epoch 91/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1282.7710 - mae: 1282.7710
Epoch 92/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1273.4619 - mae: 1273.4619
Epoch 93/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1282.6943 - mae: 1282.6943
Epoch 94/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1256.7208 - mae: 1256.7208
Epoch 95/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1253.4178 - mae: 1253.4178
Epoch 96/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1272.0968 - mae: 1272.0968
Epoch 97/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1274.1998 - mae: 1274.1998
Epoch 98/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1269.1116 - mae: 1269.1116
Epoch 99/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1252.7312 - mae: 1252.7312
Epoch 100/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1238.8909 - mae: 1238.8909
Epoch 101/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1250.4414 - mae: 1250.4414
Epoch 102/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1236.9589 - mae: 1236.9589
Epoch 103/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1246.9147 - mae: 1246.9147
Epoch 104/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1269.3938 - mae: 1269.3938
Epoch 105/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1257.1356 - mae: 1257.1356
Epoch 106/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1292.3446 - mae: 1292.3446
Epoch 107/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1271.8799 - mae: 1271.8799
Epoch 108/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1294.8683 - mae: 1294.8683
Epoch 109/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1240.4852 - mae: 1240.4852
Epoch 110/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1240.8994 - mae: 1240.8994
Epoch 111/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1242.9425 - mae: 1242.9425
Epoch 112/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1250.2830 - mae: 1250.2830
Epoch 113/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1238.6542 - mae: 1238.6542
Epoch 114/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1231.4316 - mae: 1231.4316
Epoch 115/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1248.5714 - mae: 1248.5714
Epoch 116/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1260.4233 - mae: 1260.4233
Epoch 117/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1294.3466 - mae: 1294.3466
Epoch 118/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1273.5770 - mae: 1273.5770
Epoch 119/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1255.7399 - mae: 1255.7399
Epoch 120/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1235.1947 - mae: 1235.1947
Epoch 121/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1254.8859 - mae: 1254.8859
Epoch 122/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1270.5470 - mae: 1270.5470
Epoch 123/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1239.8456 - mae: 1239.8456
Epoch 124/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1271.8876 - mae: 1271.8876
Epoch 125/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1280.9563 - mae: 1280.9563
Epoch 126/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1248.7554 - mae: 1248.7554
Epoch 127/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1241.1364 - mae: 1241.1364
Epoch 128/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1251.8274 - mae: 1251.8274
Epoch 129/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1277.8771 - mae: 1277.8771
Epoch 130/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1239.8505 - mae: 1239.8505
Epoch 131/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1251.3960 - mae: 1251.3960
Epoch 132/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1262.2351 - mae: 1262.2351
Epoch 133/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1293.1807 - mae: 1293.1807
Epoch 134/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1274.6263 - mae: 1274.6263
Epoch 135/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1270.0540 - mae: 1270.0540
Epoch 136/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1277.0597 - mae: 1277.0597
Epoch 137/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1260.9929 - mae: 1260.9929
Epoch 138/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1243.4208 - mae: 1243.4208
Epoch 139/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1253.2288 - mae: 1253.2288
Epoch 140/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1266.1814 - mae: 1266.1814
Epoch 141/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1265.8870 - mae: 1265.8870
Epoch 142/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1254.2117 - mae: 1254.2117
Epoch 143/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1252.9058 - mae: 1252.9058
Epoch 144/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1247.6774 - mae: 1247.6774
Epoch 145/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1258.0985 - mae: 1258.0985
Epoch 146/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1262.6346 - mae: 1262.6346
Epoch 147/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1253.7395 - mae: 1253.7395
Epoch 148/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1290.9633 - mae: 1290.9633
Epoch 149/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1258.6147 - mae: 1258.6147
Epoch 150/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1272.6483 - mae: 1272.6483
Epoch 151/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1269.0386 - mae: 1269.0386
Epoch 152/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1260.2690 - mae: 1260.2690
Epoch 153/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1244.9895 - mae: 1244.9895
Epoch 154/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1248.0537 - mae: 1248.0537
Epoch 155/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1264.5571 - mae: 1264.5571
Epoch 156/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1257.1547 - mae: 1257.1547
Epoch 157/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1270.9707 - mae: 1270.9707
Epoch 158/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1308.4226 - mae: 1308.4226
Epoch 159/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1245.6719 - mae: 1245.6719
Epoch 160/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1255.9369 - mae: 1255.9369
Epoch 161/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1261.6613 - mae: 1261.6613
Epoch 162/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1241.3077 - mae: 1241.3077
Epoch 163/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1245.6527 - mae: 1245.6527
Epoch 164/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1259.3612 - mae: 1259.3612
Epoch 165/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1249.6775 - mae: 1249.6775
Epoch 166/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1272.6216 - mae: 1272.6216
Epoch 167/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1254.8148 - mae: 1254.8148
Epoch 168/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1250.2667 - mae: 1250.2667
Epoch 169/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1245.7770 - mae: 1245.7770
Epoch 170/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1248.3351 - mae: 1248.3351
Epoch 171/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1251.1954 - mae: 1251.1954
Epoch 172/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1281.9142 - mae: 1281.9142
Epoch 173/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1266.6741 - mae: 1266.6741
Epoch 174/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1238.0054 - mae: 1238.0054
Epoch 175/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1240.8909 - mae: 1240.8909
Epoch 176/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1241.3718 - mae: 1241.3718
Epoch 177/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1272.3907 - mae: 1272.3907
Epoch 178/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1312.2284 - mae: 1312.2284
Epoch 179/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1276.0160 - mae: 1276.0160
Epoch 180/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1258.1648 - mae: 1258.1648
Epoch 181/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1263.2081 - mae: 1263.2081
Epoch 182/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1237.3295 - mae: 1237.3295
Epoch 183/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1254.8907 - mae: 1254.8907
Epoch 184/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1263.6616 - mae: 1263.6616
Epoch 185/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1285.3308 - mae: 1285.3308
Epoch 186/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1265.0511 - mae: 1265.0511
Epoch 187/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1247.9816 - mae: 1247.9816
Epoch 188/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1253.9833 - mae: 1253.9833
Epoch 189/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1270.5157 - mae: 1270.5157
Epoch 190/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1267.5291 - mae: 1267.5291
Epoch 191/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1241.0137 - mae: 1241.0137
Epoch 192/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1231.5250 - mae: 1231.5250
Epoch 193/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1222.7633 - mae: 1222.7633
Epoch 194/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1255.7719 - mae: 1255.7719
Epoch 195/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1270.0568 - mae: 1270.0568
Epoch 196/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1263.6755 - mae: 1263.6755
Epoch 197/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1295.7949 - mae: 1295.7949
Epoch 198/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1254.2670 - mae: 1254.2670
Epoch 199/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1274.6989 - mae: 1274.6989
Epoch 200/200
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1256.5206 - mae: 1256.5206

In [5]:
input = tf.constant([1000])
input = tf.expand_dims(input, axis=-1)
model2.predict(input)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step

array([[-8.613476]], dtype=float32)

Try and improve the results we got on the insurance dataset, some things you might want to try include:

Building a larger model (how does one with 4 dense layers go?).
Increasing the number of units in each layer.
Lookup the documentation of Adam and find out what the first parameter is, what happens if you increase it by 10x?
What happens if you train for longer (say 300 epochs instead of 200)?

In [8]:
import pandas as pd

insurance = pd.read_csv("https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/refs/heads/master/insurance.csv")
insurance.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [15]:
insurance = pd.get_dummies(insurance)
insurance.head()

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,True,False,False,True,False,False,False,True
1,18,33.770,1,1725.55230,False,True,True,False,False,False,True,False
2,28,33.000,3,4449.46200,False,True,True,False,False,False,True,False
3,33,22.705,0,21984.47061,False,True,True,False,False,True,False,False
4,32,28.880,0,3866.85520,False,True,True,False,False,True,False,False

In [19]:
from sklearn.model_selection import train_test_split

X = insurance.drop("charges", axis=1)
y = insurance["charges"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [20]:
insurance_model1 = tf.keras.Sequential([
    tf.keras.layers.Dense(100, input_shape=(11,)),
    tf.keras.layers.Dense(75),
    tf.keras.layers.Dense(20),
    tf.keras.layers.Dense(1)
])

insurance_model1.compile(loss=tf.keras.losses.mae,
                         optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
                        metrics=["mae"])

insurance_model1.fit(X_train, y_train, epochs=300)

Epoch 1/300

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

34/34 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8939.4355 - mae: 8939.4355
Epoch 2/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7015.4521 - mae: 7015.4521
Epoch 3/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6456.4341 - mae: 6456.4341
Epoch 4/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6080.2983 - mae: 6080.2983
Epoch 5/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5503.6523 - mae: 5503.6523
Epoch 6/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4187.2085 - mae: 4187.2085
Epoch 7/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3987.0613 - mae: 3987.0613
Epoch 8/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3868.2495 - mae: 3868.2495
Epoch 9/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3859.9204 - mae: 3859.9204
Epoch 10/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3689.1985 - mae: 3689.1985
Epoch 11/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3612.2749 - mae: 3612.2749
Epoch 12/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3605.0471 - mae: 3605.0471
Epoch 13/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3726.8940 - mae: 3726.8940
Epoch 14/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3803.6721 - mae: 3803.6721
Epoch 15/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3845.7961 - mae: 3845.7961
Epoch 16/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3803.1272 - mae: 3803.1272
Epoch 17/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3487.7356 - mae: 3487.7356
Epoch 18/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3535.1438 - mae: 3535.1438
Epoch 19/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3424.8398 - mae: 3424.8398
Epoch 20/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3495.3254 - mae: 3495.3254
Epoch 21/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3465.8105 - mae: 3465.8105
Epoch 22/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3503.9248 - mae: 3503.9248
Epoch 23/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3387.5369 - mae: 3387.5369
Epoch 24/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3564.5828 - mae: 3564.5828
Epoch 25/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3502.6831 - mae: 3502.6831
Epoch 26/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3525.3696 - mae: 3525.3696
Epoch 27/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3599.4148 - mae: 3599.4148
Epoch 28/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3459.6230 - mae: 3459.6230
Epoch 29/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3439.9583 - mae: 3439.9583
Epoch 30/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3456.9531 - mae: 3456.9531
Epoch 31/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3482.0149 - mae: 3482.0149
Epoch 32/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3463.2764 - mae: 3463.2764
Epoch 33/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3440.9019 - mae: 3440.9019
Epoch 34/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3699.7439 - mae: 3699.7439
Epoch 35/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3758.0146 - mae: 3758.0146
Epoch 36/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3462.9966 - mae: 3462.9966
Epoch 37/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3421.5227 - mae: 3421.5227
Epoch 38/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3605.7488 - mae: 3605.7488
Epoch 39/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3452.1011 - mae: 3452.1011
Epoch 40/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3583.1707 - mae: 3583.1707
Epoch 41/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3645.9321 - mae: 3645.9321
Epoch 42/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3501.4634 - mae: 3501.4634
Epoch 43/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3453.9541 - mae: 3453.9541
Epoch 44/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3500.6548 - mae: 3500.6548
Epoch 45/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3419.0645 - mae: 3419.0645
Epoch 46/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3521.8875 - mae: 3521.8875
Epoch 47/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3438.9644 - mae: 3438.9644
Epoch 48/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3501.2234 - mae: 3501.2234
Epoch 49/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3440.8926 - mae: 3440.8926
Epoch 50/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3550.8376 - mae: 3550.8376
Epoch 51/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3484.1997 - mae: 3484.1997
Epoch 52/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3478.8948 - mae: 3478.8948
Epoch 53/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3491.2207 - mae: 3491.2207
Epoch 54/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3412.2241 - mae: 3412.2241
Epoch 55/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3480.9468 - mae: 3480.9468
Epoch 56/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3413.0298 - mae: 3413.0298
Epoch 57/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3453.7419 - mae: 3453.7419
Epoch 58/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3532.2959 - mae: 3532.2959
Epoch 59/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3403.9878 - mae: 3403.9878
Epoch 60/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3672.3257 - mae: 3672.3257
Epoch 61/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3468.0449 - mae: 3468.0449
Epoch 62/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3609.8284 - mae: 3609.8284
Epoch 63/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3419.4927 - mae: 3419.4927
Epoch 64/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3517.3828 - mae: 3517.3828
Epoch 65/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3643.0354 - mae: 3643.0354
Epoch 66/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3489.1853 - mae: 3489.1853
Epoch 67/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3513.2390 - mae: 3513.2390
Epoch 68/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3533.9238 - mae: 3533.9238
Epoch 69/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3401.7881 - mae: 3401.7881
Epoch 70/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3600.5291 - mae: 3600.5291
Epoch 71/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3640.6672 - mae: 3640.6672
Epoch 72/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3572.6809 - mae: 3572.6809
Epoch 73/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3423.8679 - mae: 3423.8679
Epoch 74/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3469.1458 - mae: 3469.1458
Epoch 75/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3423.8201 - mae: 3423.8201
Epoch 76/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3511.8953 - mae: 3511.8953
Epoch 77/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3607.1230 - mae: 3607.1230
Epoch 78/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3441.0347 - mae: 3441.0347
Epoch 79/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3392.3699 - mae: 3392.3699
Epoch 80/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3501.4351 - mae: 3501.4351
Epoch 81/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3410.2122 - mae: 3410.2122
Epoch 82/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3446.6348 - mae: 3446.6348
Epoch 83/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3448.9465 - mae: 3448.9465
Epoch 84/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3570.3237 - mae: 3570.3237
Epoch 85/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3444.6929 - mae: 3444.6929
Epoch 86/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3408.3521 - mae: 3408.3521
Epoch 87/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3446.9233 - mae: 3446.9233
Epoch 88/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3727.2427 - mae: 3727.2427
Epoch 89/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3452.6660 - mae: 3452.6660
Epoch 90/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3466.3623 - mae: 3466.3623
Epoch 91/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3467.3501 - mae: 3467.3501
Epoch 92/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3412.9504 - mae: 3412.9504
Epoch 93/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3415.2227 - mae: 3415.2227
Epoch 94/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3478.0149 - mae: 3478.0149
Epoch 95/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3620.7205 - mae: 3620.7205
Epoch 96/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3438.0269 - mae: 3438.0269
Epoch 97/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3434.2480 - mae: 3434.2480
Epoch 98/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3663.1924 - mae: 3663.1924
Epoch 99/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3388.7012 - mae: 3388.7012
Epoch 100/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3430.6997 - mae: 3430.6997
Epoch 101/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3409.8276 - mae: 3409.8276
Epoch 102/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3383.6299 - mae: 3383.6299
Epoch 103/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3416.3198 - mae: 3416.3198
Epoch 104/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3492.3909 - mae: 3492.3909
Epoch 105/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3388.3647 - mae: 3388.3647
Epoch 106/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3416.4753 - mae: 3416.4753
Epoch 107/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3459.2759 - mae: 3459.2759
Epoch 108/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3475.9646 - mae: 3475.9646
Epoch 109/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3478.2957 - mae: 3478.2957
Epoch 110/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3392.7048 - mae: 3392.7048
Epoch 111/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3512.0217 - mae: 3512.0217
Epoch 112/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3463.2773 - mae: 3463.2773
Epoch 113/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3462.2268 - mae: 3462.2268
Epoch 114/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3416.9690 - mae: 3416.9690
Epoch 115/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3580.4031 - mae: 3580.4031
Epoch 116/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3468.8289 - mae: 3468.8289
Epoch 117/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3414.1819 - mae: 3414.1819
Epoch 118/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3475.5232 - mae: 3475.5232
Epoch 119/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3455.5613 - mae: 3455.5613
Epoch 120/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3447.5615 - mae: 3447.5615
Epoch 121/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3525.4041 - mae: 3525.4041
Epoch 122/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3432.3831 - mae: 3432.3831
Epoch 123/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3644.9463 - mae: 3644.9463
Epoch 124/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3376.7283 - mae: 3376.7283
Epoch 125/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3456.6768 - mae: 3456.6768
Epoch 126/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3548.2058 - mae: 3548.2058
Epoch 127/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3409.9802 - mae: 3409.9802
Epoch 128/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3558.4873 - mae: 3558.4873
Epoch 129/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3441.6765 - mae: 3441.6765
Epoch 130/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3438.9409 - mae: 3438.9409
Epoch 131/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3506.9099 - mae: 3506.9099
Epoch 132/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3418.5530 - mae: 3418.5530
Epoch 133/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3373.4919 - mae: 3373.4919
Epoch 134/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3377.3210 - mae: 3377.3210
Epoch 135/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3379.9805 - mae: 3379.9805
Epoch 136/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3476.0195 - mae: 3476.0195
Epoch 137/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3370.1172 - mae: 3370.1172
Epoch 138/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3388.4973 - mae: 3388.4973
Epoch 139/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3558.3425 - mae: 3558.3425
Epoch 140/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3448.7244 - mae: 3448.7244
Epoch 141/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3495.3811 - mae: 3495.3811
Epoch 142/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3410.9158 - mae: 3410.9158
Epoch 143/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3441.0857 - mae: 3441.0857
Epoch 144/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3408.6541 - mae: 3408.6541
Epoch 145/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3495.2324 - mae: 3495.2324
Epoch 146/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3424.8857 - mae: 3424.8857
Epoch 147/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3422.0266 - mae: 3422.0266
Epoch 148/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3525.8450 - mae: 3525.8450
Epoch 149/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3460.8608 - mae: 3460.8608
Epoch 150/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3407.5723 - mae: 3407.5723
Epoch 151/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3638.6294 - mae: 3638.6294
Epoch 152/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3474.2468 - mae: 3474.2468
Epoch 153/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3499.3110 - mae: 3499.3110
Epoch 154/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3534.5486 - mae: 3534.5486
Epoch 155/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3483.7146 - mae: 3483.7146
Epoch 156/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3480.7876 - mae: 3480.7876
Epoch 157/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3441.5386 - mae: 3441.5386
Epoch 158/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3550.9600 - mae: 3550.9600
Epoch 159/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3809.7390 - mae: 3809.7390
Epoch 160/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3455.8594 - mae: 3455.8594
Epoch 161/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3371.5522 - mae: 3371.5522
Epoch 162/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3405.6509 - mae: 3405.6509
Epoch 163/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3369.7170 - mae: 3369.7170
Epoch 164/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3496.8372 - mae: 3496.8372
Epoch 165/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3392.1680 - mae: 3392.1680
Epoch 166/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3423.9243 - mae: 3423.9243
Epoch 167/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3356.9597 - mae: 3356.9597
Epoch 168/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3426.2146 - mae: 3426.2146
Epoch 169/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3478.3323 - mae: 3478.3323
Epoch 170/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3379.8940 - mae: 3379.8940
Epoch 171/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3405.9714 - mae: 3405.9714
Epoch 172/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3464.5071 - mae: 3464.5071
Epoch 173/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3483.3201 - mae: 3483.3201
Epoch 174/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3428.7356 - mae: 3428.7356
Epoch 175/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3442.7192 - mae: 3442.7192
Epoch 176/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3626.1636 - mae: 3626.1636
Epoch 177/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3447.0793 - mae: 3447.0793
Epoch 178/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3497.3208 - mae: 3497.3208
Epoch 179/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3458.5969 - mae: 3458.5969
Epoch 180/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3486.7681 - mae: 3486.7681
Epoch 181/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3420.0527 - mae: 3420.0527
Epoch 182/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3413.3030 - mae: 3413.3030
Epoch 183/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3421.5178 - mae: 3421.5178
Epoch 184/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3395.6951 - mae: 3395.6951
Epoch 185/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3410.5603 - mae: 3410.5603
Epoch 186/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3612.7681 - mae: 3612.7681
Epoch 187/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3370.9746 - mae: 3370.9746
Epoch 188/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3530.4656 - mae: 3530.4656
Epoch 189/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3449.3276 - mae: 3449.3276
Epoch 190/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3607.1741 - mae: 3607.1741
Epoch 191/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3398.5742 - mae: 3398.5742
Epoch 192/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3437.1023 - mae: 3437.1023
Epoch 193/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3459.7634 - mae: 3459.7634
Epoch 194/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3460.0132 - mae: 3460.0132
Epoch 195/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3365.1658 - mae: 3365.1658
Epoch 196/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3352.5896 - mae: 3352.5896
Epoch 197/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3473.8396 - mae: 3473.8396
Epoch 198/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3418.6282 - mae: 3418.6282
Epoch 199/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3403.3958 - mae: 3403.3958
Epoch 200/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3420.2559 - mae: 3420.2559
Epoch 201/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3426.0564 - mae: 3426.0564
Epoch 202/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3415.8579 - mae: 3415.8579
Epoch 203/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3588.1252 - mae: 3588.1252
Epoch 204/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3470.1392 - mae: 3470.1392
Epoch 205/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3395.9258 - mae: 3395.9258
Epoch 206/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3445.6875 - mae: 3445.6875
Epoch 207/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3400.5010 - mae: 3400.5010
Epoch 208/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3416.5679 - mae: 3416.5679
Epoch 209/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3477.1538 - mae: 3477.1538
Epoch 210/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3672.2019 - mae: 3672.2019
Epoch 211/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3454.2563 - mae: 3454.2563
Epoch 212/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3511.9709 - mae: 3511.9709
Epoch 213/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3455.4148 - mae: 3455.4148
Epoch 214/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3398.6372 - mae: 3398.6372
Epoch 215/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3516.9282 - mae: 3516.9282
Epoch 216/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3402.1736 - mae: 3402.1736
Epoch 217/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3388.0051 - mae: 3388.0051
Epoch 218/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3353.7693 - mae: 3353.7693
Epoch 219/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3396.9392 - mae: 3396.9392
Epoch 220/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3422.9370 - mae: 3422.9370
Epoch 221/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3456.8740 - mae: 3456.8740
Epoch 222/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3377.6748 - mae: 3377.6748
Epoch 223/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3400.2283 - mae: 3400.2283
Epoch 224/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3403.2139 - mae: 3403.2139
Epoch 225/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3464.5015 - mae: 3464.5015
Epoch 226/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3410.2942 - mae: 3410.2942
Epoch 227/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3462.4136 - mae: 3462.4136
Epoch 228/300
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3380.5317 - mae: 3380.5317
Epoch 229/300

In [30]:
import numpy as np

y_preds = insurance_model1.predict(X_test)

y_test = np.array(y_test)

y_preds, y_test

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

(array([[ 3463.7617],
        [33301.9   ],
        [ 8637.884 ],
        [10325.554 ],
        [33996.145 ],
        [ 5570.7427],
        [11611.634 ],
        [39264.277 ],
        [ 4538.291 ],
        [ 5424.792 ],
        [30044.918 ],
        [29400.387 ],
        [ 4481.287 ],
        [ 5365.364 ],
        [ 6193.8926],
        [ 4620.965 ],
        [36343.145 ],
        [ 2569.4153],
        [12363.876 ],
        [12852.47  ],
        [38554.125 ],
        [10459.192 ],
        [ 7824.4365],
        [13775.361 ],
        [ 5342.0015],
        [ 2600.8955],
        [ 4365.541 ],
        [ 6495.6123],
        [ 1774.8182],
        [ 9836.408 ],
        [12848.771 ],
        [ 8607.875 ],
        [ 8570.194 ],
        [10457.512 ],
        [ 3995.1726],
        [ 5213.3135],
        [10362.568 ],
        [38932.207 ],
        [ 4706.7153],
        [ 6449.6167],
        [13375.713 ],
        [ 7506.0405],
        [30075.174 ],
        [30795.943 ],
        [ 9833.525 ],
        [30138.865 ],
        [ 4118.0557],
        [13629.15  ],
        [10975.668 ],
        [ 9513.825 ],
        [ 8156.153 ],
        [ 1788.0168],
        [12782.479 ],
        [10996.312 ],
        [10430.334 ],
        [ 3159.3962],
        [ 3558.5374],
        [35629.1   ],
        [11849.765 ],
        [ 6776.3022],
        [15005.856 ],
        [37744.652 ],
        [ 3849.8696],
        [13840.697 ],
        [12282.806 ],
        [35391.055 ],
        [ 3481.4365],
        [41808.895 ],
        [ 9043.632 ],
        [ 5262.765 ],
        [ 2486.0063],
        [ 7626.3193],
        [40753.406 ],
        [ 8353.809 ],
        [29304.86  ],
        [30834.035 ],
        [ 2636.0295],
        [41306.523 ],
        [33953.414 ],
        [ 9358.823 ],
        [29115.086 ],
        [10565.222 ],
        [11192.754 ],
        [ 9701.598 ],
        [34615.152 ],
        [12138.434 ],
        [13840.967 ],
        [ 7914.538 ],
        [ 1489.3846],
        [ 4962.3447],
        [34951.01  ],
        [36665.016 ],
        [ 4375.768 ],
        [ 8473.813 ],
        [14429.127 ],
        [ 4064.57  ],
        [ 8097.135 ],
        [ 9134.243 ],
        [12390.458 ],
        [ 2500.0215],
        [13533.633 ],
        [29661.877 ],
        [ 3201.6687],
        [ 7182.3364],
        [ 3634.5933],
        [ 5891.5884],
        [29532.037 ],
        [37251.562 ],
        [ 2552.9102],
        [11856.688 ],
        [14698.629 ],
        [11614.173 ],
        [ 5114.826 ],
        [10021.8   ],
        [ 8528.5625],
        [ 6315.3784],
        [ 9558.882 ],
        [ 8604.423 ],
        [ 5253.0884],
        [ 7156.6997],
        [39900.418 ],
        [36523.887 ],
        [ 5465.994 ],
        [ 9599.666 ],
        [ 4215.2915],
        [ 6852.1094],
        [ 2738.071 ],
        [ 3292.2258],
        [39784.32  ],
        [11814.744 ],
        [39242.4   ],
        [ 5430.168 ],
        [10175.201 ],
        [12110.492 ],
        [12013.517 ],
        [13215.797 ],
        [13841.637 ],
        [ 4890.006 ],
        [13100.7295],
        [ 7980.6865],
        [ 8825.898 ],
        [ 6784.7896],
        [ 3285.4128],
        [ 9263.852 ],
        [ 9523.754 ],
        [11160.551 ],
        [41831.105 ],
        [ 6432.188 ],
        [41165.95  ],
        [ 8576.277 ],
        [40692.15  ],
        [29506.764 ],
        [ 2158.5605],
        [ 8850.531 ],
        [35933.    ],
        [ 3737.3435],
        [ 8314.471 ],
        [31515.066 ],
        [ 5292.5933],
        [ 1871.5883],
        [ 8994.375 ],
        [ 9510.703 ],
        [ 7869.1387],
        [40232.426 ],
        [11960.348 ],
        [12351.156 ],
        [12504.525 ],
        [ 5544.7563],
        [ 2381.7878],
        [ 7508.083 ],
        [ 6321.3296],
        [10724.389 ],
        [ 5717.0986],
        [29682.812 ],
        [38159.484 ],
        [ 5046.4766],
        [ 9717.839 ],
        [12904.449 ],
        [13669.707 ],
        [ 7146.0757],
        [11095.684 ],
        [ 3052.153 ],
        [ 4171.154 ],
        [ 5053.7275],
        [11527.399 ],
        [ 7719.794 ],
        [12191.476 ],
        [34458.9   ],
        [13810.987 ],
        [13013.39  ],
        [10033.075 ],
        [33445.086 ],
        [ 6470.4575],
        [ 4030.5674],
        [41056.48  ],
        [ 5880.428 ],
        [ 9686.086 ],
        [ 5990.4014],
        [ 7909.221 ],
        [ 2034.3302],
        [ 4642.886 ],
        [40831.56  ],
        [ 6384.6216],
        [ 6975.7285],
        [ 5484.74  ],
        [35225.34  ],
        [33110.51  ],
        [11634.384 ],
        [ 9243.314 ],
        [37040.457 ],
        [13209.702 ],
        [36177.504 ],
        [13352.543 ],
        [ 1450.7347],
        [ 1681.8649],
        [ 4753.2573],
        [32536.54  ],
        [13141.253 ],
        [ 1774.4818],
        [39064.395 ],
        [ 7015.6426],
        [ 4242.269 ],
        [ 6349.851 ],
        [ 4971.016 ],
        [13913.76  ],
        [ 2704.9763],
        [ 8668.56  ],
        [ 6290.646 ],
        [13616.613 ],
        [ 2418.0574],
        [36007.438 ],
        [31883.83  ],
        [11154.054 ],
        [ 2353.5278],
        [ 9252.656 ],
        [ 7797.7476],
        [12001.869 ],
        [ 2020.4319],
        [ 1675.8633],
        [ 8295.    ],
        [ 8945.012 ],
        [41654.027 ],
        [ 3417.091 ],
        [34289.375 ],
        [ 9478.376 ],
        [ 8067.2544],
        [ 9651.1875],
        [ 7209.846 ],
        [ 4296.202 ],
        [ 9545.778 ],
        [ 9289.862 ],
        [29133.744 ],
        [ 6062.7227],
        [10523.591 ],
        [ 6922.875 ],
        [ 6751.5747],
        [36957.41  ],
        [ 5752.5117],
        [29522.625 ],
        [10533.565 ],
        [13705.58  ],
        [ 6921.8525],
        [ 5252.774 ],
        [10676.807 ],
        [33544.305 ],
        [ 6922.587 ],
        [ 6093.8667],
        [12867.21  ]], dtype=float32),
 array([24059.68  , 32734.186 ,  7986.475 ,  8823.985 , 19361.998 ,
         4058.1162, 11520.1   , 43921.184 ,  3558.6204,  4237.1265,
        39722.746 , 12829.455 ,  3021.809 , 21984.47  ,  4462.7217,
         3353.284 , 21771.342 ,  1633.9618, 11763.001 , 13415.038 ,
        24106.912 , 10096.97  ,  6457.8433, 13405.391 ,  4719.7363,
         2331.519 ,  3260.199 , 20420.605 ,  1628.471 ,  8124.408 ,
        12638.195 ,  7985.815 ,  7153.5537,  9487.645 ,  2974.126 ,
         4134.0825,  9377.904 , 24869.836 ,  3490.549 ,  4320.4106,
        13143.865 ,  6123.569 , 17560.379 , 14571.891 ,  9182.17  ,
        36898.734 ,  3443.064 , 36910.61  , 26392.26  ,  7740.337 ,
         6664.686 ,  1137.011 , 13012.209 , 10141.136 ,  9414.92  ,
         2719.2798, 10795.9375, 39125.332 , 10450.552 ,  5012.471 ,
        15612.193 , 23807.24  ,  3378.91  , 13844.797 , 11881.358 ,
        18767.738 ,  2789.0574, 47305.305 ,  8302.536 , 16796.412 ,
         7323.735 ,  6933.242 , 47403.88  ,  7222.786 , 16232.847 ,
        38344.566 ,  2102.2646, 29330.982 , 20234.855 ,  8219.204 ,
        13844.506 , 25656.576 , 10436.096 ,  8280.623 , 21082.16  ,
        11735.879 , 14007.222 ,  6496.886 ,  1711.0269,  5080.096 ,
        39047.285 , 41676.082 ,  3227.121 ,  6775.961 , 15161.534 ,
         2498.4143,  6770.1924,  8428.069 , 11365.952 ,  1967.0227,
        14449.8545, 34617.84  ,  1826.843 ,  5584.3057,  2416.955 ,
         3935.18  , 17081.08  , 22218.115 , 21595.383 , 11305.935 ,
        36580.28  ,  9432.926 ,  3366.6697,  9225.257 ,  6986.697 ,
        11737.849 , 14478.33  ,  6781.354 ,  4435.094 ,  5124.1885,
        46255.113 , 39597.406 ,  3972.9248,  8116.68  ,  2867.1196,
         5375.038 ,  2207.6975,  1984.4532, 43578.938 , 10825.254 ,
        27533.912 ,  4185.0977, 20878.785 , 11488.317 , 12142.578 ,
        13390.559 , 14382.709 ,  3238.4358, 11538.421 ,  6238.298 ,
         7640.309 , 19214.705 ,  2639.043 ,  7954.517 , 32108.662 ,
         9872.701 , 49577.664 ,  4883.866 , 47896.793 ,  6373.557 ,
        47055.53  , 16884.924 ,  1261.442 ,  8582.303 , 19023.26  ,
         2473.334 ,  7201.7007, 18310.742 ,  3471.4097,  1719.4363,
         7731.4272,  8596.828 ,  6555.0703, 26926.514 , 11830.607 ,
        33471.973 , 11743.935 ,  4719.524 ,  1629.8335,  5630.458 ,
         4670.64  ,  8569.861 ,  3693.428 , 33750.293 , 41919.098 ,
        17878.9   ,  8240.59  , 12928.791 , 14394.558 ,  6184.2993,
         9964.06  ,  2137.6536,  3353.4702,  4340.441 , 10796.351 ,
         6746.7427, 11658.379 , 37701.875 , 30166.62  , 13451.122 ,
         9301.894 , 37079.37  ,  5138.257 ,  3309.7925, 28950.469 ,
         5312.17  ,  7731.858 ,  5693.4307,  5846.9175,  1622.1885,
         4391.652 , 45710.207 ,  5003.853 ,  6059.173 ,  4718.2036,
        37829.723 , 35491.64  , 10601.632 ,  8627.541 , 42211.137 ,
        13457.961 , 21223.676 , 12981.346 ,  1621.3402,  1704.7002,
         4234.927 , 16657.717 , 12643.378 , 11884.049 , 47269.855 ,
         5272.176 ,  3213.622 ,  5125.216 ,  4428.8877, 14043.477 ,
         2045.6853,  7209.4917, 12404.879 , 14254.608 ,  2585.269 ,
        21259.379 , 19933.457 , 25992.82  ,  1664.9996,  7749.1562,
         7228.216 , 11837.16  ,  1621.8827,  1704.5681,  5757.4136,
         7626.993 , 48517.562 ,  3861.2097, 18608.262 ,  7727.2534,
         6079.6714,  7448.404 ,  5488.262 ,  3732.625 ,  8615.3   ,
         8269.044 , 15518.181 ,  4779.6025,  9290.14  ,  5484.4673,
         5266.3657, 39727.613 ,  4931.647 , 34779.613 ,  9617.662 ,
        13822.803 ,  4762.329 ,  4040.5583, 10156.783 , 18765.875 ,
         4686.3887, 24671.664 , 12269.688 ], dtype=float32))